import { StyleSheet } from "react-native";

import { colors, shadows } from "@/styles/theme";

export const styles = StyleSheet.create({
  page: {
    width: "100%",
    maxWidth: 430,
    alignSelf: "center",
    gap: 16,
    paddingBottom: 52,
  },
  logo: {
    borderRadius: 26,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(184,95,123,0.14)",
    ...shadows.soft,
  },
  capsuleMark: {
    position: "relative",
    overflow: "hidden",
    borderColor: "rgba(255,255,255,0.74)",
    backgroundColor: "transparent",
    alignItems: "center",
    justifyContent: "center",
    boxShadow: "0 12px 24px rgba(113, 81, 91, 0.1)",
  },
  capsuleMarkComplete: {
    boxShadow: "0 15px 28px rgba(113, 81, 91, 0.14)",
  },
  capsuleMarkImage: {
    position: "absolute",
    left: 0,
    top: 0,
    width: "100%",
    height: "100%",
  },
  capsuleIconCenter: {
    position: "relative",
    width: "58%",
    height: "68%",
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.44)",
  },
  topBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 14,
  },
  topText: {
    flex: 1,
    gap: 3,
  },
  topTitle: {
    color: colors.ink,
    fontSize: 23,
    lineHeight: 29,
    fontWeight: "800",
  },
  topSubtitle: {
    color: colors.muted,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "500",
  },
  card: {
    backgroundColor: "#fff",
    borderColor: "rgba(184,95,123,0.1)",
    borderWidth: 1,
    borderRadius: 28,
    padding: 22,
    gap: 14,
    ...shadows.panel,
  },
  softCard: {
    backgroundColor: "#fff",
  },
  primaryButton: {
    minHeight: 56,
    borderRadius: 24,
    backgroundColor: colors.accent,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
    paddingHorizontal: 18,
    boxShadow: "0 14px 26px rgba(184, 95, 123, 0.18)",
    elevation: 3,
  },
  primaryText: {
    color: "#fff",
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "800",
  },
  secondaryButton: {
    minHeight: 48,
    borderRadius: 999,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
    paddingHorizontal: 16,
  },
  secondaryButtonActive: {
    backgroundColor: colors.accent,
    borderColor: colors.accent,
  },
  secondaryTextActive: {
    color: "#fff",
  },
  dangerButton: {
    backgroundColor: "#fff2f0",
    borderColor: "#eac8c2",
  },
  primaryTextBase: {
    fontWeight: "800",
  },
  secondaryText: {
    color: colors.accentDark,
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "800",
  },
  dangerText: {
    color: colors.accentDark,
  },
  pressed: {
    opacity: 0.84,
    transform: [{ translateY: 1 }],
  },
  disabled: {
    opacity: 0.5,
  },
  input: {
    minHeight: 52,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: "#fff",
    paddingHorizontal: 16,
    paddingVertical: 12,
    color: colors.ink,
    fontSize: 15,
    outlineStyle: "none" as never,
  },
  coupleGroup: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
    flexWrap: "nowrap",
  },
  avatarWrap: {
    width: 96,
    alignItems: "center",
    gap: 8,
  },
  avatar: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 5,
    borderColor: "rgba(255,255,255,0.9)",
    boxShadow: "0 12px 24px rgba(141, 116, 124, 0.13), inset 0 1px 10px rgba(184,95,123,0.06)",
    overflow: "hidden",
  },
  avatarImage: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    width: "100%",
    height: "100%",
  },
  avatarShine: {
    position: "absolute",
    left: 4,
    right: 4,
    top: 4,
    bottom: 4,
    borderRadius: 32,
    backgroundImage: "linear-gradient(145deg, #fff 0%, #f6f1f3 54%, #f8e8ee 100%)" as never,
  },
  avatarText: {
    position: "absolute",
    bottom: 12,
    color: colors.accentDark,
    fontSize: 15,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  avatarName: {
    color: colors.ink,
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "800",
    textAlign: "center",
  },
  coupleConnector: {
    width: 62,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: -20,
  },
  connectorLine: {
    flex: 1,
    height: 1,
    borderStyle: "dashed",
    borderWidth: 1,
    borderColor: "rgba(184,95,123,0.16)",
  },
  coupleSpark: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.panelSoft,
    alignItems: "center",
    justifyContent: "center",
  },
  moodGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  moodChip: {
    minHeight: 44,
    borderRadius: 999,
    paddingHorizontal: 17,
    paddingVertical: 11,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
  },
  moodChipMotion: {
    borderRadius: 999,
    borderWidth: 1,
    overflow: "hidden",
  },
  moodText: {
    color: colors.muted,
    fontSize: 14,
    fontWeight: "700",
  },
  moodTextActive: {
    color: "#fff",
  },
  moodSpark: {
    color: "#fff",
    fontSize: 12,
    lineHeight: 14,
    fontWeight: "800",
  },
  stateBox: {
    minHeight: 168,
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    padding: 20,
    borderRadius: 28,
    backgroundColor: colors.panelSoft,
    borderWidth: 1,
    borderColor: "rgba(184,95,123,0.08)",
  },
  stateTitle: {
    color: colors.ink,
    fontSize: 17,
    lineHeight: 22,
    fontWeight: "800",
  },
  stateText: {
    color: colors.muted,
    fontSize: 14,
    lineHeight: 20,
    textAlign: "center",
  },
  eventCard: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 10,
    alignItems: "center",
    padding: 14,
    borderRadius: 22,
    backgroundColor: "#fff",
    borderColor: colors.border,
    borderWidth: 1,
  },
  eventTitle: {
    color: colors.ink,
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "800",
  },
  eventMeta: {
    color: colors.muted,
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "700",
  },
  eventDate: {
    color: colors.accentDark,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "800",
  },
  messageCard: {
    gap: 9,
    padding: 15,
    borderRadius: 24,
    backgroundColor: "#fff",
    borderColor: colors.border,
    borderWidth: 1,
  },
  checkinCard: {
    gap: 8,
    padding: 15,
    borderRadius: 24,
    backgroundColor: colors.panelSoft,
    borderColor: colors.border,
    borderWidth: 1,
  },
  checkinCardCompact: {
    height: 132,
    justifyContent: "flex-start",
  },
  checkinMood: {
    alignSelf: "flex-start",
    color: colors.accentDark,
    backgroundColor: colors.accentSoft,
    borderRadius: 999,
    overflow: "hidden",
    paddingHorizontal: 10,
    paddingVertical: 5,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "800",
  },
  messageTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 8,
  },
  messageAuthor: {
    color: colors.ink,
    fontSize: 13,
    fontWeight: "800",
  },
  messageBody: {
    color: colors.ink,
    fontSize: 15,
    lineHeight: 22,
  },
  checkinBodyCompact: {
    fontSize: 14,
    lineHeight: 20,
    overflow: "hidden",
  },
  interaction: {
    width: "100%",
    height: 60,
    borderRadius: 20,
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
    paddingHorizontal: 4,
    paddingVertical: 4,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.64)",
  },
  interactionMotion: {
    width: "23%",
    flexGrow: 0,
    flexShrink: 0,
  },
  interactionIconSlot: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: "rgba(255,255,255,0.7)",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  interactionIcon: {
    width: 22,
    height: 22,
  },
  interactionText: {
    color: colors.ink,
    fontSize: 11,
    lineHeight: 14,
    fontWeight: "900",
    textAlign: "center",
  },
  settingRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    minHeight: 56,
  },
  settingIcon: {
    width: 36,
    height: 36,
    borderRadius: 16,
    backgroundColor: colors.panelSoft,
    alignItems: "center",
    justifyContent: "center",
  },
  settingIconDanger: {
    backgroundColor: colors.accentSoft,
  },
  settingText: {
    flex: 1,
    color: colors.ink,
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "700",
  },
  notification: {
    width: 42,
    height: 42,
    borderRadius: 17,
    backgroundColor: "rgba(255,255,255,0.78)",
    borderWidth: 1,
    borderColor: "rgba(184,95,123,0.14)",
    alignItems: "center",
    justifyContent: "center",
  },
  floatingEntryButton: {
    alignItems: "center",
    justifyContent: "center",
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "rgba(255,255,255,0.9)",
    borderWidth: 1,
    borderColor: "rgba(184,95,123,0.16)",
    boxShadow: "0 16px 34px rgba(99, 74, 83, 0.16)",
    elevation: 4,
  },
  floatingEntryButtonPressed: {
    transform: [{ scale: 0.98 }],
  },
  floatingEntryIcon: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(247, 226, 232, 0.9)",
  },
});
