import { Platform, StyleSheet } from "react-native";

import { colors } from "@/styles/theme";

export const photoStyles = StyleSheet.create({
  photoAlbumCard: {
    gap: 14,
    borderRadius: 32,
    backgroundColor: "rgba(255,255,255,0.76)",
    borderColor: "rgba(255,255,255,0.86)",
    boxShadow: "0 10px 20px rgba(90,68,76,0.04), inset 0 1px 2px rgba(255,255,255,0.9)",
  },
  photoAlbumHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  photoAlbumTitleGroup: {
    gap: 2,
  },
  photoAlbumMeta: {
    color: colors.muted,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "700",
  },
  photoAlbumHeaderActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  photoAlbumViewAllButton: {
    minHeight: 34,
    borderRadius: 999,
    paddingHorizontal: 12,
    backgroundColor: colors.accentSoft,
    borderWidth: 1,
    borderColor: "rgba(184,95,123,0.14)",
    alignItems: "center",
    justifyContent: "center",
  },
  photoAlbumViewAllText: {
    color: colors.accentDark,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "900",
  },
  photoAlbumUploadButton: {
    position: "relative",
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.panelSoft,
    borderWidth: 1,
    borderColor: "rgba(184,95,123,0.13)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  photoNativeFileInput: {
    position: "absolute",
    inset: 0,
    width: "100%",
    height: "100%",
    opacity: 0,
    cursor: "pointer",
    zIndex: 4,
  },
  photoAlbumGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    rowGap: 12,
    paddingTop: 4,
    paddingBottom: 2,
  },
  photoAlbumThumb: {
    width: "31%",
    aspectRatio: 0.72,
    position: "relative",
    borderRadius: 7,
    backgroundColor: "#fffefc",
    borderWidth: 1,
    borderColor: "rgba(214,177,159,0.2)",
    paddingTop: 6,
    paddingHorizontal: 6,
    paddingBottom: 24,
    boxShadow: "0 10px 18px rgba(82, 61, 66, 0.1)",
  },
  photoAlbumThumbPressable: {
    width: "100%",
    height: "100%",
    borderRadius: 4,
    overflow: "hidden",
    backgroundColor: "#f6eee8",
  },
  photoAlbumImage: {
    width: "100%",
    height: "100%",
  },
  photoAlbumMoreOverlay: {
    ...StyleSheet.absoluteFill,
    backgroundColor: "rgba(82,61,66,0.46)",
    alignItems: "center",
    justifyContent: "center",
  },
  photoAlbumMoreText: {
    color: "#fff",
    fontSize: 16,
    lineHeight: 21,
    fontWeight: "900",
  },
  photoAlbumDeleteBadge: {
    position: "absolute",
    right: 6,
    top: 6,
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: "rgba(82,61,66,0.78)",
    alignItems: "center",
    justifyContent: "center",
  },
  photoAlbumCaption: {
    position: "absolute",
    left: 6,
    right: 6,
    bottom: 6,
    color: "rgba(103,82,86,0.74)",
    fontSize: 10,
    lineHeight: 13,
    fontWeight: "700",
    textAlign: "center",
    fontFamily: Platform.select({ web: "'Courier New', Courier, monospace", default: undefined }) as never,
  },
  photoAlbumEmpty: {
    minHeight: 132,
    width: "31%",
    borderRadius: 7,
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: "rgba(112,94,98,0.26)",
    backgroundColor: "#fffdf9",
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "flex-start",
    padding: 9,
    gap: 5,
    boxShadow: "0 10px 18px rgba(82,61,66,0.07)",
  },
  photoAlbumEmptyCamera: {
    width: 46,
    height: 42,
    borderRadius: 12,
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: "rgba(112,94,98,0.24)",
    alignItems: "center",
    justifyContent: "center",
  },
  photoAlbumEmptyTitle: {
    color: "rgba(103,82,86,0.74)",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "800",
    textAlign: "center",
  },
  photoAlbumEmptyText: {
    color: "rgba(103,82,86,0.58)",
    fontSize: 10,
    lineHeight: 14,
    fontWeight: "600",
    textAlign: "center",
  },
  photoPreviewLayer: {
    position: "fixed",
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    zIndex: 40,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 16,
    paddingTop: "calc(18px + env(safe-area-inset-top))" as never,
    paddingBottom: "calc(22px + env(safe-area-inset-bottom))" as never,
  },
  photoPreviewBackdrop: {
    ...StyleSheet.absoluteFill,
    backgroundColor: "rgba(54,38,45,0.52)",
  },
  photoPreviewCard: {
    position: "relative",
    width: "100%",
    maxWidth: 520,
    maxHeight: "100%",
    borderRadius: 32,
    padding: 14,
    backgroundColor: "rgba(255,252,250,0.98)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.8)",
    boxShadow: "0 30px 72px rgba(74,47,58,0.3), inset 0 1px 1px rgba(255,255,255,0.88)",
    elevation: 12,
    gap: 12,
  },
  photoPreviewHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10,
  },
  photoPreviewNavButton: {
    position: "absolute",
    top: "50%",
    width: 38,
    height: 38,
    marginTop: -19,
    borderRadius: 19,
    backgroundColor: "rgba(255,255,255,0.92)",
    borderWidth: 1,
    borderColor: "rgba(184,95,123,0.12)",
    alignItems: "center",
    justifyContent: "center",
    boxShadow: "0 10px 18px rgba(74,47,58,0.14)",
  },
  photoPreviewNavLeft: {
    left: 10,
  },
  photoPreviewNavRight: {
    right: 10,
  },
  photoPreviewNavText: {
    color: colors.accentDark,
    fontSize: 24,
    lineHeight: 26,
    fontWeight: "800",
    marginTop: -2,
  },
  photoPreviewCounterPill: {
    minHeight: 28,
    borderRadius: 999,
    paddingHorizontal: 11,
    backgroundColor: colors.accentSoft,
    alignItems: "center",
    justifyContent: "center",
  },
  photoPreviewCounterText: {
    color: colors.accentDark,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "800",
  },
  photoPreviewCloseIcon: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: "rgba(255,255,255,0.9)",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(184,95,123,0.12)",
  },
  photoPreviewCloseIconText: {
    color: colors.accentDark,
    fontSize: 18,
    lineHeight: 20,
    fontWeight: "900",
  },
  photoPreviewFrame: {
    position: "relative",
    width: "100%",
    aspectRatio: 1,
    minHeight: 240,
    borderRadius: 24,
    overflow: "hidden",
    backgroundColor: "#f8efe9",
    alignItems: "center",
    justifyContent: "center",
  },
  photoPreviewImage: {
    width: "100%",
    height: "100%",
  },
  photoPreviewMeta: {
    gap: 4,
    paddingHorizontal: 4,
  },
  photoPreviewTitle: {
    color: colors.ink,
    fontSize: 18,
    lineHeight: 24,
    fontWeight: "900",
    textAlign: "center",
  },
  photoPreviewBody: {
    color: colors.muted,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "600",
    textAlign: "center",
  },
  photoPreviewActions: {
    flexDirection: "row",
    gap: 10,
  },
  photoPreviewDelete: {
    flex: 1,
    minHeight: 48,
    borderRadius: 999,
    backgroundColor: colors.panelSoft,
    borderWidth: 1,
    borderColor: "rgba(184,95,123,0.12)",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 6,
  },
  photoPreviewDeleteText: {
    color: colors.accentDark,
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "900",
  },
  photoPreviewClose: {
    flex: 1,
    minHeight: 48,
    borderRadius: 999,
    backgroundColor: colors.accent,
    alignItems: "center",
    justifyContent: "center",
    boxShadow: "0 14px 24px rgba(184,95,123,0.2)",
  },
  photoPreviewCloseText: {
    color: "#fff",
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "900",
  },
  photoPreviewStrip: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  photoPreviewStripThumb: {
    width: 54,
    height: 54,
    borderRadius: 14,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(184,95,123,0.08)",
    backgroundColor: colors.panelSoft,
  },
  photoPreviewStripThumbActive: {
    borderColor: colors.accent,
    borderWidth: 2,
  },
  photoPreviewStripImage: {
    width: "100%",
    height: "100%",
  },
});
