import { Platform, StyleSheet } from "react-native";

import { creationStyles } from "@/features/home/homeCreationStyles";
import { memoryStyles } from "@/features/home/homeMemoryStyles";
import { overlayStyles } from "@/features/home/homeOverlayStyles";
import { photoStyles } from "@/features/home/homePhotoStyles";
import { colors } from "@/styles/theme";

const baseStyles = StyleSheet.create({
  stack: {
    gap: 14,
    paddingBottom: 18,
  },
  todayStoryScreen: {
    gap: 14,
    paddingBottom: 22,
  },
  shellAvatarRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    height: 58,
  },
  shellAvatar: {
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: "rgba(255,255,255,0.82)",
    borderWidth: 2,
    borderColor: "rgba(255,255,255,0.94)",
  },
  shellAvatarSecond: {
    marginLeft: -12,
    backgroundColor: "rgba(248,232,239,0.9)",
  },
  shellHeroTitle: {
    width: 126,
    height: 17,
    borderRadius: 999,
    backgroundColor: "rgba(184,95,123,0.14)",
    marginTop: 2,
  },
  shellHeroNumber: {
    width: 116,
    height: 46,
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,0.78)",
  },
  shellHeroDate: {
    width: 104,
    height: 14,
    borderRadius: 999,
    backgroundColor: "rgba(129,111,116,0.12)",
  },
  shellSectionTitle: {
    width: 74,
    height: 18,
    borderRadius: 999,
    backgroundColor: "rgba(42,36,38,0.1)",
  },
  shellSmallText: {
    width: 92,
    height: 13,
    borderRadius: 999,
    backgroundColor: "rgba(129,111,116,0.12)",
  },
  shellPill: {
    width: 82,
    height: 28,
    borderRadius: 999,
    backgroundColor: colors.accentSoft,
  },
  shellStatusValue: {
    width: 72,
    height: 20,
    borderRadius: 999,
    backgroundColor: "rgba(184,95,123,0.12)",
  },
  shellInteractionButton: {
    width: "23.6%",
    aspectRatio: 0.82,
    borderRadius: 18,
    backgroundColor: colors.panelSoft,
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderWidth: 1,
    borderColor: "rgba(184,95,123,0.08)",
  },
  shellInteractionIcon: {
    width: 34,
    height: 34,
    borderRadius: 14,
    backgroundColor: "rgba(255,255,255,0.82)",
  },
  shellInteractionText: {
    width: 42,
    height: 11,
    borderRadius: 999,
    backgroundColor: "rgba(129,111,116,0.12)",
  },
  shellRoundButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.panelSoft,
    borderWidth: 1,
    borderColor: "rgba(184,95,123,0.1)",
  },
  shellPhotoThumb: {
    backgroundColor: "rgba(248,232,239,0.76)",
  },
  shellMessageInput: {
    minHeight: 74,
    borderRadius: 20,
    backgroundColor: colors.panelSoft,
    borderWidth: 1,
    borderColor: "rgba(184,95,123,0.08)",
  },
  shellPrimaryButton: {
    minHeight: 48,
    borderRadius: 999,
    backgroundColor: "rgba(211,117,150,0.62)",
  },
  heroCard: {
    position: "relative",
    overflow: "hidden",
    paddingTop: 16,
    paddingBottom: 18,
    gap: 16,
    borderRadius: 32,
    backgroundColor: "rgba(255, 255, 255, 0.76)",
    borderColor: "rgba(255,255,255,0.86)",
    backgroundImage: "radial-gradient(circle at 14% 6%, rgba(255, 214, 227, 0.46), rgba(255,255,255,0.08) 42%), radial-gradient(circle at 88% 18%, rgba(255, 246, 209, 0.48), rgba(255,255,255,0.08) 40%)" as never,
    boxShadow: "0 10px 20px rgba(90,68,76,0.04), inset 0 1px 2px rgba(255,255,255,0.9)",
  },
  heroTopRow: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  brandRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flex: 1,
  },
  heroBrand: {
    color: "#6b404b",
    fontSize: 20,
    lineHeight: 25,
    fontWeight: "800",
  },
  heroBrandSub: {
    color: "rgba(92,70,76,0.58)",
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "600",
  },
  heroLovePanel: {
    position: "relative",
    width: "100%",
    minHeight: 258,
    borderRadius: 30,
    paddingTop: 22,
    paddingHorizontal: 14,
    paddingBottom: 12,
    alignItems: "center",
    overflow: "hidden",
    backgroundColor: "rgba(255,255,255,0.38)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.72)",
    boxShadow: "inset 0 1px 1px rgba(255,255,255,0.86), 0 16px 32px rgba(90,68,76,0.035)",
  },
  heroAvatarPair: {
    width: "100%",
    alignItems: "center",
    opacity: 0.92,
    transform: [{ scale: 0.96 }],
  },
  heroLoveBody: {
    alignItems: "center",
    marginTop: -8,
    zIndex: 2,
  },
  heroLoveTitle: {
    color: "rgba(96,71,77,0.68)",
    fontSize: 15,
    lineHeight: 19,
    fontWeight: "600",
  },
  heroNumberRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "center",
    gap: 6,
    marginTop: -2,
  },
  heroLoveNumber: {
    color: "#764851",
    fontSize: 58,
    lineHeight: 63,
    fontWeight: "500",
    textAlign: "center",
    fontFamily: Platform.select({ web: "Georgia, 'Times New Roman', serif", default: undefined }) as never,
    textShadowColor: "rgba(223, 128, 158, 0.16)",
    textShadowOffset: { width: 0, height: 5 },
    textShadowRadius: 12,
  },
  heroLoveUnit: {
    color: "#764851",
    fontSize: 16,
    lineHeight: 24,
    fontWeight: "700",
    textAlign: "center",
    marginBottom: 6,
  },
  heroWave: {
    position: "absolute",
    top: 48,
    left: 18,
    right: 18,
    opacity: 0.8,
    filter: "drop-shadow(0 0 6px rgba(238,138,170,0.28))" as never,
  },
  heroRelationText: {
    color: colors.muted,
    fontSize: 13,
    lineHeight: 16,
    fontWeight: "600",
    marginTop: 0,
  },
  loveNumberRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "center",
    gap: 6,
  },
  loveNumber: {
    color: colors.accentDark,
    fontSize: 46,
    lineHeight: 50,
    fontWeight: "800",
    textAlign: "center",
  },
  loveUnit: {
    color: colors.ink,
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "700",
    textAlign: "center",
    marginBottom: 6,
  },
  startedText: {
    color: "rgba(100,76,82,0.7)",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "600",
  },
  countdownText: {
    color: colors.accentDark,
    fontSize: 15,
    lineHeight: 22,
    fontWeight: "800",
  },
  sectionTitle: {
    color: colors.ink,
    fontSize: 19,
    lineHeight: 25,
    fontWeight: "800",
  },
  sectionTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  capsuleIcon: {
    fontSize: 20,
    lineHeight: 24,
  },
  centerTitle: {
    color: colors.ink,
    fontSize: 18,
    lineHeight: 24,
    fontWeight: "800",
    textAlign: "center",
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  sectionTitleGroup: {
    flex: 1,
    gap: 2,
    minWidth: 0,
  },
  sectionMetaText: {
    color: colors.muted,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "800",
  },
  bodyText: {
    color: colors.muted,
    fontSize: 15,
    lineHeight: 22,
    fontWeight: "400",
  },
  profileHero: {
    alignItems: "center",
    gap: 10,
  },
  moodStatusCard: {
    position: "relative",
    overflow: "hidden",
    borderRadius: 32,
    paddingVertical: 17,
    gap: 14,
    backgroundColor: "rgba(255, 255, 255, 0.76)",
    borderColor: "rgba(255,255,255,0.86)",
    boxShadow: "0 10px 20px rgba(90,68,76,0.04), inset 0 1px 2px rgba(255,255,255,0.9)",
  },
  loveLetterEntryCard: {
    position: "relative",
    width: "92%",
    minHeight: 84,
    borderRadius: 10,
    paddingHorizontal: 16,
    paddingTop: 38,
    paddingBottom: 10,
    marginTop: 12,
    backgroundColor: "#fff9f5",
    borderWidth: 1,
    borderColor: "rgba(226,189,171,0.46)",
    alignItems: "center",
    justifyContent: "center",
    overflow: "visible",
    boxShadow: "0 12px 22px rgba(90,68,76,0.12), inset 0 1px 1px rgba(255,255,255,0.9)",
  },
  loveLetterEntryCardPressed: {
    transform: [{ scale: 0.98 }],
    opacity: 0.9,
    backgroundColor: "rgba(255, 255, 255, 0.52)",
  },
  envelopeFlap: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    height: 48,
    backgroundColor: "#fffdf9",
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(210,171,154,0.38)",
    transform: [{ skewY: "-6deg" }],
    boxShadow: "0 5px 12px rgba(90,68,76,0.07)",
  },
  envelopeLeftFold: {
    position: "absolute",
    left: 0,
    bottom: 0,
    width: "52%",
    height: 52,
    borderBottomLeftRadius: 10,
    borderRightWidth: 1,
    borderRightColor: "rgba(210,171,154,0.28)",
    transform: [{ skewY: "-14deg" }],
    backgroundColor: "rgba(255,248,243,0.82)",
  },
  envelopeRightFold: {
    position: "absolute",
    right: 0,
    bottom: 0,
    width: "52%",
    height: 52,
    borderBottomRightRadius: 10,
    borderLeftWidth: 1,
    borderLeftColor: "rgba(210,171,154,0.28)",
    transform: [{ skewY: "14deg" }],
    backgroundColor: "rgba(255,248,243,0.82)",
  },
  envelopeSeal: {
    position: "absolute",
    top: 29,
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: "rgba(237,143,169,0.72)",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "rgba(255,222,165,0.88)",
    boxShadow: "0 8px 14px rgba(184,95,123,0.18), inset 0 1px 2px rgba(255,255,255,0.7)",
  },
  envelopeSealInner: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,196,213,0.7)",
  },
  loveLetterEntryTitle: {
    color: "#a4586d",
    fontSize: 20,
    lineHeight: 25,
    fontWeight: "800",
    marginTop: 6,
    fontFamily: Platform.select({ web: "Georgia, 'Times New Roman', serif", default: undefined }) as never,
  },
  loveLetterEntryText: {
    color: "rgba(112,83,90,0.58)",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "600",
    textAlign: "center",
  },
  profileName: {
    color: colors.ink,
    fontSize: 20,
    lineHeight: 26,
    fontWeight: "800",
  },
  feedbackInput: {
    minHeight: 150,
    paddingTop: 15,
    textAlignVertical: "top",
  },
  aboutTitle: {
    color: colors.ink,
    fontSize: 24,
    lineHeight: 30,
    fontWeight: "800",
    textAlign: "center",
  },
  toggleRow: {
    minHeight: 54,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 14,
  },
  disabledRow: {
    opacity: 0.45,
  },
  settingLabel: {
    color: colors.ink,
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "700",
  },
  switchTrack: {
    width: 50,
    height: 30,
    borderRadius: 15,
    backgroundColor: "#eadfe1",
    padding: 3,
    justifyContent: "center",
  },
  switchTrackActive: {
    backgroundColor: colors.accent,
  },
  switchThumb: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "#fff",
  },
  switchThumbActive: {
    transform: [{ translateX: 20 }],
  },
  infoRow: {
    minHeight: 50,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 14,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(184,95,123,0.08)",
  },
  infoRowValue: {
    color: colors.muted,
    fontSize: 14,
    lineHeight: 19,
    fontWeight: "800",
  },
  petSizeSegment: {
    minHeight: 48,
    borderRadius: 999,
    padding: 4,
    backgroundColor: "rgba(255,248,251,0.9)",
    borderWidth: 1,
    borderColor: "rgba(184,95,123,0.12)",
    flexDirection: "row",
    gap: 4,
  },
  petSizeOption: {
    flex: 1,
    minHeight: 40,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
  },
  petSizeOptionActive: {
    backgroundColor: colors.accent,
    boxShadow: "0 8px 18px rgba(184,95,123,0.18)",
  },
  petSizeOptionText: {
    color: colors.muted,
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "900",
  },
  petSizeOptionTextActive: {
    color: "#fff",
  },
  profileStatsGrid: {
    width: "100%",
    flexDirection: "row",
    gap: 8,
  },
  statusGrid: {
    flexDirection: "row",
    gap: 10,
  },
  interactionCountPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  interactionCountText: {
    color: colors.accentDark,
    fontSize: 11,
    lineHeight: 14,
    fontWeight: "900",
  },
  homeMessageInput: {
    height: 150,
    paddingTop: 10,
    paddingRight: 16,
    paddingLeft: 16,
    textAlignVertical: "top",
    borderWidth: 0,
    backgroundColor: "transparent",
    boxShadow: "none" as never,
    color: "#6f4c55",
    fontSize: 16,
    lineHeight: 30,
    zIndex: 2,
  },
  homeMessageList: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  homeMessageHeaderActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  homeMessageViewAllButton: {
    minHeight: 30,
    borderRadius: 999,
    paddingHorizontal: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.72)",
    borderWidth: 1,
    borderColor: "rgba(184,95,123,0.12)",
  },
  homeMessageViewAllText: {
    color: colors.accentDark,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "900",
  },
  notificationRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(184,95,123,0.08)",
  },
  notificationIcon: {
    width: 36,
    height: 36,
    borderRadius: 16,
    backgroundColor: colors.accentSoft,
    alignItems: "center",
    justifyContent: "center",
  },
  notificationCopy: {
    flex: 1,
    gap: 2,
    minWidth: 0,
  },
  todayCapsuleBody: {
    minHeight: 86,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    borderRadius: 20,
    backgroundColor: colors.panelSoft,
    borderWidth: 1,
    borderColor: "rgba(184,95,123,0.08)",
    padding: 12,
  },
  todayCapsuleBodyGuide: {
    borderColor: "rgba(184,95,123,0.14)",
  },
  todayCapsuleBodyPressed: {
    transform: [{ scale: 0.985 }],
  },
  moodOrb: {
    width: 58,
    height: 50,
    borderRadius: 25,
    backgroundColor: "transparent",
    alignItems: "center",
    justifyContent: "center",
  },
  moodOrbText: {
    fontSize: 20,
    lineHeight: 24,
  },
  moodOrbImage: {
    width: 26,
    height: 26,
    borderRadius: 10,
  },
  todayCapsuleCopy: {
    flex: 1,
    gap: 5,
  },
  todayCapsuleLabel: {
    color: colors.muted,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "700",
  },
  todayCapsuleText: {
    color: colors.ink,
    fontSize: 15,
    lineHeight: 21,
    fontWeight: "600",
  },
  capsuleStatusPill: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(184,95,123,0.2)",
    paddingHorizontal: 10,
    paddingVertical: 7,
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  capsuleStatusText: {
    color: colors.accentDark,
    fontSize: 13,
    lineHeight: 17,
    fontWeight: "800",
  },
  infoIcon: {
    width: 42,
    height: 42,
    borderRadius: 17,
    backgroundColor: colors.accentSoft,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  infoImageIcon: {
    width: 42,
    height: 42,
    resizeMode: "contain",
  },
  headerIcon: {
    width: 34,
    height: 34,
    borderRadius: 14,
    resizeMode: "contain",
  },
  infoLabel: {
    color: colors.muted,
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "800",
  },
  infoValue: {
    color: colors.accentDark,
    fontSize: 20,
    lineHeight: 26,
    fontWeight: "800",
  },
  statusPill: {
    flex: 1,
    borderRadius: 16,
    backgroundColor: "#fff9f9",
    paddingVertical: 6,
    paddingHorizontal: 10,
    gap: 1,
    borderWidth: 1,
    borderColor: "rgba(184,95,123,0.08)",
  },
  statusLabel: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: "800",
  },
  statusValue: {
    color: colors.ink,
    fontSize: 15,
    fontWeight: "800",
  },
  bubbleMoodSlot: {
    flex: 1,
    minHeight: 94,
    borderRadius: 34,
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    overflow: "visible",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.84)",
    boxShadow: "0 10px 22px rgba(90,68,76,0.06), inset 0 1px 2px rgba(255,255,255,0.88)",
  },
  bubbleMoodSlotWarm: {
    backgroundColor: "rgba(255,226,233,0.72)",
    backgroundImage: "radial-gradient(circle at 28% 20%, rgba(255,255,255,0.72), rgba(255,226,233,0.22) 46%, rgba(255,214,226,0.52))" as never,
  },
  bubbleMoodSlotCool: {
    backgroundColor: "rgba(238,235,250,0.76)",
    backgroundImage: "radial-gradient(circle at 30% 18%, rgba(255,255,255,0.72), rgba(240,237,250,0.28) 44%, rgba(222,220,246,0.56))" as never,
  },
  bubbleMoodSlotActive: {
    transform: [{ rotate: "-0.7deg" }],
  },
  bubbleMoodLobeOne: {
    position: "absolute",
    left: 22,
    top: -10,
    width: 56,
    height: 42,
    borderRadius: 26,
    backgroundColor: "rgba(255,255,255,0.34)",
  },
  bubbleMoodLobeTwo: {
    position: "absolute",
    right: 16,
    top: 2,
    width: 50,
    height: 38,
    borderRadius: 24,
    backgroundColor: "rgba(255,255,255,0.26)",
  },
  bubbleMoodLobeThree: {
    position: "absolute",
    left: 9,
    bottom: 12,
    width: 34,
    height: 26,
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,0.2)",
  },
  bubbleMoodIcon: {
    width: 26,
    height: 22,
    borderRadius: 14,
    backgroundColor: "rgba(255,255,255,0.54)",
    alignItems: "center",
    justifyContent: "center",
  },
  interactionGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    alignItems: "center",
    columnGap: 0,
    rowGap: 6,
  },
  customQuickComposer: {
    gap: 10,
    borderRadius: 24,
    padding: 12,
    backgroundColor: "#fff9fb",
    borderWidth: 1,
    borderColor: "rgba(184,95,123,0.1)",
  },
  customQuickInput: {
    minHeight: 46,
    paddingVertical: 12,
  },
  customQuickActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 10,
  },
  homeMessageBoardCard: {
    position: "relative",
    overflow: "hidden",
    borderRadius: 32,
    paddingTop: 18,
    paddingBottom: 14,
    backgroundColor: "rgba(255,250,248,0.82)",
    borderColor: "rgba(255,255,255,0.86)",
    boxShadow: "0 10px 20px rgba(90,68,76,0.04), inset 0 1px 2px rgba(255,255,255,0.9)",
  },
  messageBoardAnchorWrap: {
    gap: 12,
  },
  messagePaperLines: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 6,
    bottom: 0,
    borderRadius: 20,
    backgroundImage: "repeating-linear-gradient(0deg, transparent 0px, transparent 29px, rgba(218,139,160,0.12) 29px, rgba(218,139,160,0.12) 30px)" as never,
    zIndex: 1,
  },
  messagePaperFold: {
    position: "absolute",
    right: -1,
    top: -1,
    width: 48,
    height: 48,
    backgroundColor: "#fff7f7",
    borderLeftWidth: 1,
    borderBottomWidth: 1,
    borderColor: "rgba(218,139,160,0.14)",
    transform: [{ rotate: "12deg" }, { translateX: 18 }, { translateY: -15 }],
    boxShadow: "-7px 8px 16px rgba(90,68,76,0.06)",
  },
  homeMessagePaperInput: {
    position: "relative",
    height: 180,
    borderRadius: 20,
    backgroundColor: "rgba(255,255,255,0.28)",
    overflow: "hidden",
  },
  homeMessageSendButton: {
    minHeight: 36,
    borderRadius: 999,
    paddingHorizontal: 16,
    backgroundColor: "rgba(225,128,156,0.78)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
    boxShadow: "0 8px 14px rgba(184,95,123,0.16), inset 0 1px 1px rgba(255,255,255,0.6)",
  },
  homeMessageComposer: {
    gap: 6,
  },
  homeMessageActionRow: {
    flexDirection: "row",
    justifyContent: "flex-end",
  },
  homeMessageSendButtonDisabled: {
    opacity: 0.48,
  },
  homeMessageSendText: {
    color: "#fff",
    fontSize: 13,
    lineHeight: 17,
    fontWeight: "900",
  },
  stickyMemoCard: {
    position: "relative",
    width: "48%",
    minHeight: 100,
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingTop: 18,
    paddingBottom: 10,
    backgroundColor: "#fff1c9",
    borderWidth: 1,
    borderColor: "rgba(201,158,105,0.18)",
    transform: [{ rotate: "-1.2deg" }],
    boxShadow: "0 10px 18px rgba(82,61,66,0.08)",
  },
  stickyMemoTape: {
    position: "absolute",
    left: "35%",
    top: -8,
    width: 42,
    height: 16,
    borderRadius: 3,
    backgroundColor: "rgba(255,223,215,0.7)",
    transform: [{ rotate: "2deg" }],
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.48)",
  },
  stickyMemoTop: {
    gap: 2,
    marginBottom: 6,
  },
  stickyMemoAuthor: {
    color: "#8a5a4d",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "900",
  },
  stickyMemoMeta: {
    color: "rgba(116,88,81,0.54)",
    fontSize: 10,
    lineHeight: 14,
    fontWeight: "700",
  },
  stickyMemoBody: {
    color: "#5f4542",
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "600",
  },
  stickyMemoDelete: {
    alignSelf: "flex-start",
    marginTop: 8,
    minHeight: 28,
    borderRadius: 999,
    paddingHorizontal: 8,
    backgroundColor: "rgba(255,255,255,0.44)",
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  stickyMemoDeleteText: {
    color: colors.accentDark,
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "900",
  },
  creationCrystalButton: {
    position: "relative",
    width: 76,
    height: 92,
    borderRadius: 38,
    alignItems: "center",
    justifyContent: "center",
    overflow: "visible",
  },
  creationCrystalAura: {
    position: "absolute",
    width: 76,
    height: 76,
    borderRadius: 38,
    backgroundColor: "rgba(246,169,196,0.24)",
    boxShadow: "0 0 24px rgba(246,169,196,0.38)",
  },
  creationCrystalSheen: {
    position: "absolute",
    width: 68,
    height: 68,
    borderRadius: 34,
    backgroundColor: "rgba(255,255,255,0.32)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.78)",
    backgroundImage: "radial-gradient(circle at 30% 20%, rgba(255,255,255,0.88), rgba(255,255,255,0.2) 34%, rgba(245,163,195,0.34) 72%, rgba(238,203,245,0.24))" as never,
    boxShadow: "0 18px 32px rgba(90,68,76,0.16), inset 0 1px 2px rgba(255,255,255,0.92)",
  },
  creationCrystalPets: {
    width: 52,
    height: 52,
    borderRadius: 26,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(191,144,169,0.18)",
  },
  creationCrystalHeart: {
    position: "absolute",
    right: 9,
    bottom: 10,
  },
  creationCrystalStar: {
    position: "absolute",
    right: 0,
    top: 3,
    width: 25,
    height: 25,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,211,139,0.5)",
    boxShadow: "0 4px 10px rgba(231,174,83,0.26)",
  },
  creationCrystalLabel: {
    position: "absolute",
    bottom: 0,
    minWidth: 58,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
    overflow: "hidden",
    backgroundColor: "rgba(255,255,255,0.6)",
    color: colors.accentDark,
    textAlign: "center",
    fontSize: 12,
    lineHeight: 15,
    fontWeight: "900",
  },
  capsulePreviewCard: {
    position: "relative",
    overflow: "hidden",
    minHeight: 192,
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    paddingVertical: 20,
    paddingHorizontal: 18,
    borderRadius: 32,
    backgroundColor: "rgba(255,253,251,0.78)",
    borderColor: "rgba(255,255,255,0.88)",
    boxShadow: "0 16px 34px rgba(116,74,89,0.055), inset 0 1px 2px rgba(255,255,255,0.94)",
  },
  capsulePreviewGlow: {
    position: "absolute",
    width: 220,
    height: 126,
    borderRadius: 999,
    opacity: 0.2,
    transform: [{ translateY: -12 }],
  },
  capsulePreviewMoodWash: {
    position: "absolute",
    width: 154,
    height: 92,
    borderRadius: 999,
    opacity: 0.16,
    transform: [{ translateY: -16 }],
  },
  capsulePreviewStageRing: {
    position: "absolute",
    width: 154,
    height: 154,
    borderRadius: 77,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.76)",
    backgroundColor: "rgba(255,255,255,0.16)",
    boxShadow: "inset 0 1px 2px rgba(255,255,255,0.82)",
    transform: [{ translateY: -17 }],
  },
  capsulePreviewSparkOne: {
    position: "absolute",
    right: 58,
    top: 30,
    width: 9,
    height: 9,
    borderRadius: 5,
    backgroundColor: "rgba(255,213,224,0.86)",
    boxShadow: "0 0 12px rgba(217,120,150,0.18)",
  },
  capsulePreviewSparkTwo: {
    position: "absolute",
    left: 58,
    top: 74,
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: "rgba(255,242,199,0.9)",
    boxShadow: "0 0 10px rgba(231,185,99,0.18)",
  },
  capsulePreviewStage: {
    position: "relative",
    zIndex: 1,
    width: 114,
    height: 94,
    alignItems: "center",
    justifyContent: "center",
  },
  capsulePreviewPedestal: {
    position: "absolute",
    left: 8,
    right: 8,
    bottom: 7,
    height: 24,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.62)",
    boxShadow: "0 10px 18px rgba(82,61,66,0.06)",
  },
  capsulePreviewImage: {
    width: 36,
    height: 36,
    borderRadius: 14,
  },
  capsulePreviewMetaPill: {
    position: "relative",
    zIndex: 1,
    minHeight: 27,
    borderRadius: 999,
    paddingHorizontal: 11,
    backgroundColor: "rgba(255,255,255,0.64)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.82)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
  },
  capsulePreviewMetaText: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "900",
  },
  capsulePreviewTitle: {
    position: "relative",
    zIndex: 1,
    color: colors.ink,
    fontSize: 20,
    lineHeight: 25,
    fontWeight: "900",
    marginTop: 2,
    textAlign: "center",
  },
  capsulePreviewText: {
    position: "relative",
    zIndex: 1,
    color: colors.muted,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "700",
    textAlign: "center",
  },
  capsuleComposerHeader: {
    position: "relative",
    zIndex: 1,
    gap: 6,
    paddingRight: 38,
  },
  capsuleComposerTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  capsuleComposerSeal: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: colors.accent,
    alignItems: "center",
    justifyContent: "center",
    boxShadow: "0 8px 14px rgba(184,95,123,0.18), inset 0 1px 2px rgba(255,255,255,0.45)",
  },
  capsuleComposerHint: {
    color: colors.muted,
    fontSize: 13,
    lineHeight: 19,
    fontWeight: "700",
    textAlign: "center",
  },
  moodOptionalBlock: {
    position: "relative",
    zIndex: 1,
    gap: 10,
    borderRadius: 24,
    padding: 12,
    backgroundColor: "rgba(255,255,255,0.48)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.76)",
  },
  moodTrayHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  moodOptionalTitle: {
    color: colors.muted,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "900",
  },
  moodTrayLabel: {
    color: colors.accentDark,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "900",
    backgroundColor: "rgba(255,226,232,0.74)",
    borderRadius: 999,
    overflow: "hidden",
    paddingHorizontal: 9,
    paddingVertical: 4,
  },
  customMoodInput: {
    minHeight: 46,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.82)",
  },
  linkText: {
    color: colors.accentDark,
    fontSize: 13,
    fontWeight: "800",
  },
  activityRow: {
    flexDirection: "row",
    gap: 10,
    alignItems: "center",
  },
  activityDot: {
    width: 9,
    height: 9,
    borderRadius: 5,
    backgroundColor: colors.peach,
    marginTop: 7,
  },
  activityIconSlot: {
    width: 32,
    height: 32,
    borderRadius: 13,
    backgroundColor: colors.panelSoft,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  activityIconImage: {
    width: 30,
    height: 30,
    borderRadius: 11,
  },
  activityText: {
    flex: 1,
    gap: 2,
  },
  activityTitle: {
    color: colors.ink,
    fontSize: 15,
    lineHeight: 21,
    fontWeight: "600",
  },
  activityMeta: {
    color: colors.faint,
    fontSize: 12,
    lineHeight: 17,
  },
  swipeableActivityRow: {
    position: "relative",
    minHeight: 56,
    borderRadius: 20,
    overflow: "hidden",
    backgroundColor: "rgba(241,87,106,0.1)",
  },
  swipeableActivityAction: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    width: 82,
    alignItems: "stretch",
    justifyContent: "center",
  },
  swipeableDeleteButton: {
    flex: 1,
    minHeight: 56,
    borderRadius: 20,
    backgroundColor: "#e85d6c",
    alignItems: "center",
    justifyContent: "center",
    gap: 3,
  },
  swipeableDeleteButtonDisabled: {
    opacity: 0.72,
  },
  swipeableDeleteText: {
    color: "#fff",
    fontSize: 12,
    lineHeight: 15,
    fontWeight: "900",
  },
  swipeableActivityContent: {
    minHeight: 56,
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 10,
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.86)",
    borderWidth: 1,
    borderColor: "rgba(184,95,123,0.08)",
  },
  swipeableActivityContentStatic: {
    minHeight: 56,
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 10,
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.58)",
    borderWidth: 1,
    borderColor: "rgba(184,95,123,0.06)",
  },
  storyInput: {
    minHeight: 124,
    paddingTop: 13,
    paddingBottom: 14,
    textAlignVertical: "top",
    backgroundColor: "transparent",
    borderWidth: 0,
    boxShadow: "none",
    outlineStyle: "none" as never,
    paddingHorizontal: 0,
    fontSize: 16,
    lineHeight: 29,
  },
  createCapsuleCard: {
    position: "relative",
    overflow: "hidden",
    gap: 14,
    padding: 18,
    borderRadius: 32,
    backgroundColor: "rgba(255,253,251,0.78)",
    borderColor: "rgba(255,255,255,0.88)",
    boxShadow: "0 18px 40px rgba(82,61,66,0.065), inset 0 1px 1px rgba(255,255,255,0.92)",
  },
  createCapsuleCardWash: {
    position: "absolute",
    left: -46,
    top: -50,
    width: 164,
    height: 128,
    borderRadius: 999,
    backgroundColor: "rgba(255,220,232,0.32)",
    transform: [{ rotate: "14deg" }],
  },
  createCapsulePaperFold: {
    position: "absolute",
    right: 0,
    top: 0,
    width: 50,
    height: 50,
    borderBottomLeftRadius: 18,
    backgroundColor: "rgba(255,226,218,0.76)",
    borderLeftWidth: 1,
    borderBottomWidth: 1,
    borderColor: "rgba(222,128,154,0.14)",
    boxShadow: "-8px 8px 16px rgba(184,95,123,0.05)",
  },
  emotionCandyGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    columnGap: 0,
    rowGap: 9,
    overflow: "visible",
  },
  emotionCandyMotion: {
    width: "48%",
    flexBasis: "48%",
    maxWidth: "48%",
    overflow: "visible",
  },
  emotionCandy: {
    position: "relative",
    width: "100%",
    minHeight: 43,
    borderRadius: 999,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    paddingHorizontal: 10,
  },
  emotionCandyShine: {
    position: "absolute",
    left: 16,
    right: 34,
    top: 7,
    height: 9,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.5)",
  },
  emotionCandyLowerShade: {
    position: "absolute",
    left: 14,
    right: 14,
    bottom: -10,
    height: 18,
    borderRadius: 999,
    opacity: 0.08,
  },
  emotionCandyActiveRing: {
    ...StyleSheet.absoluteFill,
    borderRadius: 999,
    borderWidth: 1.5,
    opacity: 0.62,
  },
  emotionCandyText: {
    position: "relative",
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "900",
  },
  foldedMoodNote: {
    position: "relative",
    minHeight: 146,
    borderRadius: 24,
    backgroundColor: "#fff2ef",
    borderWidth: 1,
    borderColor: "rgba(222,128,154,0.18)",
    overflow: "hidden",
    paddingLeft: 22,
    paddingRight: 44,
    boxShadow: "0 12px 26px rgba(184,95,123,0.08), inset 0 1px 2px rgba(255,255,255,0.84)",
  },
  foldedMoodNoteFocused: {
    borderColor: "rgba(215,123,150,0.58)",
    boxShadow: "0 0 0 4px rgba(215,123,150,0.13), 0 0 28px rgba(215,123,150,0.22), inset 0 1px 2px rgba(255,255,255,0.9)",
  },
  foldedMoodNoteLines: {
    position: "absolute",
    left: 18,
    right: 12,
    top: 33,
    bottom: 13,
    backgroundImage: "repeating-linear-gradient(0deg, transparent 0px, transparent 28px, rgba(218,139,160,0.2) 28px, rgba(218,139,160,0.2) 29px)" as never,
  },
  foldedMoodNoteMarginLine: {
    position: "absolute",
    left: 15,
    top: 18,
    bottom: 16,
    width: 1,
    backgroundColor: "rgba(218,139,160,0.12)",
  },
  foldedMoodNoteFold: {
    position: "absolute",
    right: 0,
    top: 0,
    width: 42,
    height: 42,
    backgroundColor: "#ffe1dd",
    borderBottomLeftRadius: 14,
    borderLeftWidth: 1,
    borderBottomWidth: 1,
    borderColor: "rgba(222,128,154,0.18)",
  },
  foldedMoodNoteFoldShadow: {
    position: "absolute",
    right: 28,
    top: 8,
    width: 22,
    height: 38,
    borderRadius: 999,
    backgroundColor: "rgba(184,95,123,0.08)",
    transform: [{ rotate: "-35deg" }],
  },
  capsulePhotoUploadRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flexWrap: "wrap",
  },
  capsulePhotoUploadButton: {
    position: "relative",
    minHeight: 42,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.86)",
    borderWidth: 1,
    borderColor: "rgba(184,95,123,0.16)",
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    overflow: "hidden",
  },
  capsulePhotoUploadButtonDisabled: {
    opacity: 0.5,
  },
  capsulePhotoUploadText: {
    color: colors.accentDark,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "900",
  },
  capsulePhotoUploadMeta: {
    flex: 1,
    minWidth: 158,
    color: colors.faint,
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "700",
  },
  capsulePhotoPreviewRow: {
    flexDirection: "row",
    gap: 10,
  },
  capsulePhotoPreviewItem: {
    position: "relative",
    flex: 1,
    minWidth: 0,
    height: 78,
    borderRadius: 18,
    overflow: "hidden",
    backgroundColor: "rgba(255,255,255,0.66)",
    borderWidth: 1,
    borderColor: "rgba(184,95,123,0.12)",
  },
  capsulePhotoPreviewImage: {
    width: "100%",
    height: "100%",
  },
  capsulePhotoPreviewBadge: {
    position: "absolute",
    left: 6,
    top: 6,
    minHeight: 20,
    borderRadius: 999,
    paddingHorizontal: 7,
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.9)",
    borderWidth: 1,
    borderColor: "rgba(184,95,123,0.12)",
  },
  capsulePhotoPreviewBadgeText: {
    color: colors.accentDark,
    fontSize: 10,
    lineHeight: 13,
    fontWeight: "900",
  },
  capsulePhotoPreviewLabel: {
    position: "absolute",
    left: 7,
    right: 7,
    bottom: 6,
    color: "#fff",
    fontSize: 10,
    lineHeight: 13,
    fontWeight: "900",
    textShadowColor: "rgba(42,31,34,0.42)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  capsuleSaveFlight: {
    position: "absolute",
    left: 30,
    bottom: 380,
    width: 66,
    height: 42,
    borderRadius: 999,
    backgroundColor: colors.accentSoft,
    borderWidth: 2,
    borderColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 5,
    boxShadow: "0 14px 28px rgba(184,95,123,0.16)",
  },
  capsuleSaveFlightImage: {
    width: 24,
    height: 24,
    borderRadius: 9,
  },
  capsuleSaveTarget: {
    position: "absolute",
    right: 40,
    bottom: 586,
    width: 48,
    height: 48,
    borderRadius: 18,
    backgroundColor: colors.panelSoft,
    borderWidth: 1,
    borderColor: "rgba(184,95,123,0.16)",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 4,
    boxShadow: "0 10px 22px rgba(113,81,91,0.1)",
  },
  capsuleSaveTargetDay: {
    color: colors.accentDark,
    fontSize: 16,
    lineHeight: 18,
    fontWeight: "800",
  },
  capsuleSaveTargetText: {
    color: colors.muted,
    fontSize: 10,
    lineHeight: 12,
    fontWeight: "800",
  },
  emptyStatePressable: {
    borderRadius: 28,
  },
  historyCapsuleCard: {
    borderRadius: 32,
    backgroundColor: "rgba(255,255,255,0.72)",
    borderColor: "rgba(255,255,255,0.84)",
    boxShadow: "0 12px 28px rgba(82,61,66,0.045), inset 0 1px 1px rgba(255,255,255,0.88)",
  },
  stepHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  stepNumber: {
    color: colors.accentDark,
    backgroundColor: colors.accentSoft,
    borderRadius: 999,
    overflow: "hidden",
    paddingHorizontal: 10,
    paddingVertical: 5,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "800",
  },
  messageInput: {
    minHeight: 96,
    paddingTop: 15,
    textAlignVertical: "top",
  },
  letterInput: {
    minHeight: 180,
    paddingTop: 15,
    textAlignVertical: "top",
  },
  modeRow: {
    flexDirection: "row",
    gap: 10,
  },
  letterComposeHero: {
    alignItems: "center",
    gap: 14,
    overflow: "hidden",
  },
  letterEnvelopePreview: {
    width: 94,
    height: 64,
    borderRadius: 24,
    backgroundColor: colors.cream,
    borderWidth: 1,
    borderColor: "rgba(184,95,123,0.16)",
    alignItems: "center",
    justifyContent: "center",
  },
  letterReminderCard: {
    position: "relative",
    overflow: "hidden",
    alignItems: "center",
    minHeight: 420,
    paddingVertical: 28,
    gap: 12,
  },
  letterGlow: {
    position: "absolute",
    width: 250,
    height: 250,
    borderRadius: 125,
    backgroundColor: colors.accentSoft,
    opacity: 0.58,
    top: 34,
  },
  letterSenderRow: {
    position: "relative",
    zIndex: 1,
  },
  letterEnvelope: {
    position: "relative",
    zIndex: 1,
    width: 140,
    height: 96,
    borderRadius: 34,
    backgroundColor: colors.cream,
    borderWidth: 2,
    borderColor: "rgba(255,255,255,0.86)",
    alignItems: "center",
    justifyContent: "center",
    boxShadow: "0 22px 42px rgba(82,61,66,0.14)",
    transform: [{ rotate: "-3deg" }],
  },
  letterEnvelopeOpen: {
    backgroundColor: "#fff",
    transform: [{ rotate: "2deg" }, { scale: 1.03 }],
  },
  letterReminderTitle: {
    position: "relative",
    zIndex: 1,
    color: colors.ink,
    fontSize: 24,
    lineHeight: 30,
    fontWeight: "900",
    textAlign: "center",
  },
  letterReminderMeta: {
    position: "relative",
    zIndex: 1,
    color: colors.accentDark,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "800",
    textAlign: "center",
  },
  letterReminderBody: {
    position: "relative",
    zIndex: 1,
    color: colors.ink,
    fontSize: 16,
    lineHeight: 25,
    fontWeight: "500",
    textAlign: "center",
    backgroundColor: "rgba(255,255,255,0.7)",
    borderRadius: 24,
    padding: 18,
    width: "100%",
  },
  letterActionRow: {
    position: "relative",
    zIndex: 1,
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 10,
  },
  monthRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  calendarGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    rowGap: 8,
  },
  calendarSurface: {
    gap: 10,
    borderRadius: 24,
    backgroundColor: "#fffafb",
    borderWidth: 1,
    borderColor: "rgba(184,95,123,0.08)",
    padding: 12,
  },
  calendarMonthRow: {
    minHeight: 30,
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
  },
  calendarMonthText: {
    color: colors.ink,
    fontSize: 22,
    lineHeight: 28,
    fontWeight: "900",
  },
  calendarMonthMeta: {
    color: colors.muted,
    fontSize: 13,
    lineHeight: 19,
    fontWeight: "800",
  },
  weekdayGrid: {
    flexDirection: "row",
  },
  weekdayText: {
    width: "14.285%",
    color: colors.accentDark,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "900",
    textAlign: "center",
  },
  dayCell: {
    width: "14.285%",
    minHeight: 54,
    borderRadius: 16,
    backgroundColor: "transparent",
    alignItems: "center",
    justifyContent: "flex-start",
    borderWidth: 0,
    borderColor: "transparent",
    gap: 3,
    paddingTop: 2,
  },
  dayCellEmpty: {
    opacity: 0,
  },
  dayNumberBubble: {
    position: "relative",
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
  },
  dayCellMarked: {
    backgroundColor: "rgba(255,255,255,0.8)",
  },
  dayCellToday: {
    backgroundColor: colors.accentSoft,
    borderWidth: 1,
    borderColor: "rgba(184,95,123,0.14)",
  },
  dayText: {
    color: colors.muted,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "800",
  },
  dayTextToday: {
    color: colors.accentDark,
    fontWeight: "900",
  },
  dayHeartMark: {
    position: "absolute",
    right: -2,
    top: -2,
    width: 13,
    height: 13,
    borderRadius: 7,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
  dayIconSlot: {
    width: 24,
    height: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  dayCapsuleMark: {
    borderRadius: 999,
    backgroundColor: colors.accentSoft,
    borderWidth: 1,
    borderColor: "rgba(184,95,123,0.14)",
  },
  dayImageIcon: {
    width: 18,
    height: 18,
    borderRadius: 7,
    resizeMode: "contain",
  },
  dayDot: {
    width: 5,
    height: 5,
    borderRadius: 3,
    backgroundColor: colors.accentDark,
  },
  typeGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  typeChip: {
    flex: 1,
    minWidth: "42%",
    minHeight: 46,
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,0.76)",
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: "center",
    justifyContent: "center",
  },
  typeChipActive: {
    backgroundColor: colors.accentSoft,
    borderColor: "rgba(184,95,123,0.2)",
  },
  typeText: {
    color: colors.muted,
    fontSize: 14,
    fontWeight: "800",
  },
  typeTextActive: {
    color: colors.ink,
  },
  remindRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  checkbox: {
    width: 18,
    height: 18,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: "#fff",
  },
  checkboxActive: {
    backgroundColor: colors.accent,
    borderColor: colors.accent,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 16,
    backgroundColor: "rgba(255,255,255,0.78)",
    borderWidth: 1,
    borderColor: "rgba(184,95,123,0.14)",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  quietDangerArea: {
    opacity: 0.72,
    gap: 8,
    paddingHorizontal: 14,
    paddingTop: 4,
  },
  compactDanger: {
    gap: 10,
    marginTop: 8,
    opacity: 0.78,
  },
  quietDangerText: {
    color: colors.faint,
    fontSize: 12,
    lineHeight: 18,
  },
  todayCapsuleSummaryCard: {
    position: "relative",
    overflow: "hidden",
    borderRadius: 32,
    backgroundColor: "rgba(255,255,255,0.74)",
    borderColor: "rgba(255,255,255,0.86)",
    boxShadow: "0 14px 32px rgba(82,61,66,0.052), inset 0 1px 2px rgba(255,255,255,0.9)",
  },
  todayCapsuleSummaryGlow: {
    position: "absolute",
    right: -44,
    top: -42,
    width: 146,
    height: 110,
    borderRadius: 999,
    backgroundColor: "rgba(255,240,201,0.36)",
    transform: [{ rotate: "-18deg" }],
  },
  petLetterDeliveryCard: {
    position: "relative",
    minHeight: 82,
    borderRadius: 26,
    padding: 13,
    overflow: "hidden",
    backgroundColor: "rgba(255,255,255,0.9)",
    borderWidth: 1,
    borderColor: "rgba(184,95,123,0.14)",
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    boxShadow: "0 16px 28px rgba(116,74,89,0.1)",
  },
  petLetterDeliveryGlow: {
    position: "absolute",
    right: -32,
    top: -44,
    width: 126,
    height: 126,
    borderRadius: 63,
    backgroundColor: "rgba(255,223,234,0.58)",
  },
  petLetterDeliveryIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: colors.accentSoft,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.88)",
    alignItems: "center",
    justifyContent: "center",
  },
  petLetterDeliveryCopy: {
    flex: 1,
    minWidth: 0,
    gap: 3,
  },
  petLetterDeliveryTitle: {
    color: colors.ink,
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "900",
  },
  petLetterDeliveryText: {
    color: colors.muted,
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "800",
  },
  petMemoryCueCard: {
    position: "relative",
    minHeight: 82,
    borderRadius: 26,
    padding: 13,
    overflow: "hidden",
    backgroundColor: "rgba(255,255,255,0.86)",
    borderWidth: 1,
    borderColor: "rgba(150,128,190,0.14)",
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    boxShadow: "0 16px 28px rgba(82,61,116,0.08)",
  },
  petMemoryCueGlow: {
    position: "absolute",
    right: -30,
    top: -42,
    width: 126,
    height: 126,
    borderRadius: 63,
    backgroundColor: "rgba(221,214,247,0.54)",
  },
  petMemoryCueIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "rgba(240,237,248,0.9)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.88)",
    alignItems: "center",
    justifyContent: "center",
  },
  petMemoryCueCopy: {
    flex: 1,
    minWidth: 0,
    gap: 3,
  },
  petMemoryCueTitle: {
    color: colors.ink,
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "900",
  },
  petMemoryCueText: {
    color: colors.muted,
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "800",
  },
  // 1. 双人同频并排卡片样式
  doubleCapsulesRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    position: "relative",
    paddingHorizontal: 2,
    paddingTop: 2,
    gap: 8,
  },
  sideCapsuleContainer: {
    flex: 1,
    height: 138,
    borderRadius: 22,
    backgroundColor: "rgba(255,255,255,0.7)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.84)",
    overflow: "hidden",
    boxShadow: "0 10px 24px rgba(82, 61, 66, 0.05), inset 0 1px 2px rgba(255,255,255,0.78)",
  },
  sideCapsuleEmpty: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    height: "100%" as never,
    backgroundColor: "rgba(255, 255, 255, 0.38)",
    padding: 10,
  },
  sideCapsuleEmptyText: {
    color: colors.accent,
    fontSize: 13,
    fontWeight: "800",
  },
  sideCapsuleWaiting: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    height: "100%" as never,
    backgroundColor: "rgba(255, 255, 255, 0.28)",
    padding: 10,
  },
  sideCapsuleWaitingText: {
    color: colors.faint,
    fontSize: 13,
    fontWeight: "700",
    fontStyle: "italic",
  },
  doubleCapsulesConnector: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "rgba(255, 255, 255, 0.94)",
    borderWidth: 1.5,
    borderColor: "rgba(184,95,123,0.14)",
    alignItems: "center",
    justifyContent: "center",
    position: "absolute",
    left: "50%",
    marginLeft: -12,
    zIndex: 3,
    boxShadow: "0 4px 10px rgba(184, 95, 123, 0.08)",
  },
});

export const styles = {
  ...baseStyles,
  ...overlayStyles,
  ...memoryStyles,
  ...photoStyles,
  ...creationStyles,
};
