import { StyleSheet } from "react-native";

import { colors } from "@/styles/theme";

export const overlayStyles = StyleSheet.create({
  floatingReaction: {
    position: "absolute",
    left: 18,
    right: 18,
    top: 52,
    minHeight: 68,
    borderRadius: 26,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: "rgba(255,255,255,0.96)",
    borderWidth: 1,
    borderColor: "rgba(184,95,123,0.12)",
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    zIndex: 4,
    boxShadow: "0 16px 34px rgba(113,81,91,0.14)",
  },
  floatingReactionIconWrap: {
    width: 42,
    height: 42,
    borderRadius: 18,
    backgroundColor: colors.panelSoft,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  floatingReactionIcon: {
    fontSize: 20,
    lineHeight: 24,
  },
  floatingReactionImage: {
    width: 32,
    height: 32,
    borderRadius: 12,
  },
  floatingReactionCopy: {
    flex: 1,
    minWidth: 0,
    gap: 3,
  },
  floatingReactionTitle: {
    color: colors.muted,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "800",
  },
  floatingReactionText: {
    color: colors.accentDark,
    fontSize: 16,
    lineHeight: 21,
    fontWeight: "900",
  },
  floatingReactionTrack: {
    height: 5,
    borderRadius: 999,
    backgroundColor: "rgba(184,95,123,0.12)",
    overflow: "hidden",
    marginTop: 3,
  },
  floatingReactionTrackFill: {
    height: "100%",
    borderRadius: 999,
    backgroundColor: colors.accent,
  },
  floatingReactionDots: {
    width: 28,
    alignItems: "center",
    justifyContent: "center",
    gap: 3,
  },
  floatingReactionDot: {
    width: 5,
    height: 5,
    borderRadius: 3,
    backgroundColor: colors.accent,
  },
  moodPopupLayer: {
    position: "fixed" as never,
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    alignItems: "center",
    justifyContent: "flex-start",
    paddingHorizontal: 16,
    paddingTop: "calc(18px + env(safe-area-inset-top))" as never,
    zIndex: 20,
    pointerEvents: "box-none" as never,
  },
  moodPopupCard: {
    position: "relative",
    width: "100%",
    maxWidth: 390,
    overflow: "hidden",
    borderRadius: 22,
    backgroundColor: "rgba(255,255,255,0.97)",
    borderWidth: 1,
    borderColor: "rgba(184,95,123,0.13)",
    paddingVertical: 10,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    boxShadow: "0 14px 30px rgba(82, 61, 66, 0.16)",
    elevation: 9,
  },
  moodPopupGlow: {
    position: "absolute",
    width: 210,
    height: 132,
    borderRadius: 999,
    backgroundColor: colors.accentSoft,
    opacity: 0.5,
    right: -54,
    top: -42,
    transform: [{ rotate: "-8deg" }],
  },
  moodPopupIconWrap: {
    position: "relative",
    width: 40,
    height: 40,
    borderRadius: 15,
    backgroundColor: colors.panelSoft,
    borderWidth: 1,
    borderColor: "rgba(184,95,123,0.1)",
    alignItems: "center",
    justifyContent: "center",
  },
  moodPopupIcon: {
    width: 28,
    height: 28,
    borderRadius: 10,
  },
  moodPopupCopy: {
    position: "relative",
    flex: 1,
    minWidth: 0,
    gap: 1,
  },
  moodPopupEyebrow: {
    color: colors.accentDark,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "900",
  },
  moodPopupTitle: {
    color: colors.ink,
    fontSize: 17,
    lineHeight: 22,
    fontWeight: "900",
  },
  moodPopupBody: {
    color: colors.muted,
    fontSize: 14,
    lineHeight: 21,
    fontWeight: "600",
  },
  moodPopupPrimaryButton: {
    width: 38,
    height: 34,
    borderRadius: 999,
    backgroundColor: colors.accent,
    alignItems: "center",
    justifyContent: "center",
    boxShadow: "0 8px 16px rgba(184, 95, 123, 0.16)",
  },
  moodPopupPrimaryButtonWide: {
    position: "relative",
    minHeight: 34,
    borderRadius: 999,
    backgroundColor: colors.accent,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
    boxShadow: "0 8px 16px rgba(184, 95, 123, 0.16)",
  },
  moodPopupPrimaryText: {
    color: "#fff",
    fontSize: 13,
    lineHeight: 17,
    fontWeight: "900",
  },
  letterPopupLayer: {
    position: "fixed",
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 18,
    paddingTop: "calc(24px + env(safe-area-inset-top))" as never,
    paddingBottom: "calc(92px + env(safe-area-inset-bottom))" as never,
    backgroundColor: "rgba(53,38,45,0.18)",
    zIndex: 30,
    pointerEvents: "box-none",
  },
  letterPopupCard: {
    position: "relative",
    width: "100%",
    maxWidth: 390,
    minHeight: 386,
    overflow: "hidden",
    borderRadius: 34,
    paddingHorizontal: 22,
    paddingTop: 28,
    paddingBottom: 18,
    backgroundColor: "rgba(255,252,250,0.98)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.78)",
    alignItems: "center",
    gap: 9,
    boxShadow: "0 28px 70px rgba(74,47,58,0.24), inset 0 1px 1px rgba(255,255,255,0.92)",
    elevation: 12,
  },
  letterPopupHalo: {
    position: "absolute",
    width: 300,
    height: 230,
    borderRadius: 150,
    top: -58,
    backgroundImage: "radial-gradient(circle at 50% 48%, rgba(255,230,238,0.92), rgba(255,245,223,0.56) 42%, rgba(238,232,246,0.25) 70%, rgba(255,255,255,0) 100%)",
  },
  letterPopupSparkOne: {
    position: "absolute",
    width: 76,
    height: 76,
    borderRadius: 38,
    right: 28,
    top: 54,
    backgroundColor: "rgba(255,240,201,0.62)",
  },
  letterPopupSparkTwo: {
    position: "absolute",
    width: 48,
    height: 48,
    borderRadius: 24,
    left: 30,
    top: 112,
    backgroundColor: "rgba(238,232,246,0.72)",
  },
  letterPopupStamp: {
    position: "absolute",
    right: 28,
    top: 28,
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: colors.accent,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "rgba(255,255,255,0.82)",
    boxShadow: "0 10px 20px rgba(184,95,123,0.2)",
    zIndex: 2,
  },
  letterPopupEnvelope: {
    position: "relative",
    width: 142,
    height: 100,
    borderRadius: 30,
    marginTop: 8,
    backgroundColor: colors.cream,
    borderWidth: 2,
    borderColor: "rgba(255,255,255,0.9)",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    boxShadow: "0 22px 42px rgba(82,61,66,0.16)",
    transform: [{ rotate: "-2deg" }],
    zIndex: 1,
  },
  letterPopupFlap: {
    position: "absolute",
    left: -14,
    right: -14,
    top: -48,
    height: 96,
    backgroundColor: "#ffe5dc",
    borderRadius: 38,
    transform: [{ rotate: "8deg" }],
  },
  letterPopupPaper: {
    position: "absolute",
    top: 14,
    width: 88,
    height: 52,
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,0.88)",
    borderWidth: 1,
    borderColor: "rgba(184,95,123,0.1)",
    alignItems: "center",
    justifyContent: "center",
  },
  letterPopupPaperText: {
    color: colors.faint,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "900",
  },
  letterPopupEyebrow: {
    position: "relative",
    color: colors.accentDark,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "900",
    textAlign: "center",
    zIndex: 1,
  },
  letterPopupTitle: {
    position: "relative",
    color: colors.ink,
    fontSize: 23,
    lineHeight: 29,
    fontWeight: "900",
    textAlign: "center",
    zIndex: 1,
  },
  letterPopupBody: {
    position: "relative",
    color: colors.muted,
    fontSize: 15,
    lineHeight: 22,
    fontWeight: "600",
    textAlign: "center",
    maxWidth: 280,
    zIndex: 1,
  },
  letterPopupActions: {
    position: "relative",
    width: "100%",
    flexDirection: "row",
    gap: 10,
    marginTop: 8,
    zIndex: 1,
  },
  letterPopupPrimary: {
    flex: 1,
    minHeight: 48,
    borderRadius: 999,
    backgroundColor: colors.accent,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 14,
    boxShadow: "0 14px 24px rgba(184,95,123,0.2)",
  },
  letterPopupPrimaryText: {
    color: "#fff",
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "900",
    textAlign: "center",
  },
  letterPopupSecondary: {
    flex: 1,
    minHeight: 48,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.78)",
    borderWidth: 1,
    borderColor: "rgba(184,95,123,0.12)",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 14,
  },
  letterPopupSecondaryText: {
    color: colors.accentDark,
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "900",
    textAlign: "center",
  },
});
