import { StyleSheet } from "react-native";

import { colors } from "@/styles/theme";

export const creationStyles = StyleSheet.create({
  creationFloatingDock: {
    position: "fixed" as never,
    right: "max(2vw, calc(50% - 224px))" as never,
    bottom: "calc(224px + env(safe-area-inset-bottom))" as never,
    alignItems: "center",
    zIndex: 2,
  },
  creationTownPage: {
    gap: 12,
  },
  creationAssetBar: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    padding: 7,
    borderRadius: 26,
    backgroundColor: "rgba(255,255,255,0.86)",
    borderWidth: 1,
    borderColor: "rgba(184,95,123,0.14)",
    boxShadow: "0 14px 30px rgba(116,74,89,0.1)",
  },
  creationAssetChip: {
    flexGrow: 1,
    minWidth: "30%",
    minHeight: 50,
    borderRadius: 22,
    paddingHorizontal: 10,
    paddingVertical: 7,
    backgroundColor: "rgba(255,250,252,0.96)",
    borderWidth: 1,
    borderColor: "rgba(184,95,123,0.08)",
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
  },
  creationAssetChipCompact: {
    flexGrow: 0,
    minWidth: 86,
    minHeight: 40,
    borderRadius: 20,
    paddingHorizontal: 8,
    paddingVertical: 5,
    backgroundColor: "rgba(255,255,255,0.82)",
  },
  creationAssetChipPulse: {
    backgroundColor: "#fff0c9",
    borderColor: "rgba(215,162,78,0.42)",
    boxShadow: "0 10px 22px rgba(215,162,78,0.2)",
    transform: [{ translateY: -1 }],
  },
  creationAssetChipIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#FDF3D6",
    alignItems: "center",
    justifyContent: "center",
  },
  creationAssetChipIconCompact: {
    width: 28,
    height: 28,
    borderRadius: 14,
  },
  creationAssetChipCopy: {
    minWidth: 0,
  },
  creationAssetChipLabel: {
    color: colors.faint,
    fontSize: 10,
    lineHeight: 13,
    fontWeight: "900",
  },
  creationAssetChipLabelCompact: {
    fontSize: 9,
    lineHeight: 11,
  },
  creationAssetChipValue: {
    color: colors.ink,
    fontSize: 14,
    lineHeight: 17,
    fontWeight: "900",
  },
  creationAssetChipValueCompact: {
    fontSize: 13,
    lineHeight: 15,
  },
  creationRewardRibbon: {
    flexDirection: "row",
    gap: 10,
    paddingHorizontal: 2,
  },
  creationRewardPill: {
    flex: 1,
    minHeight: 58,
    borderRadius: 25,
    paddingHorizontal: 12,
    paddingVertical: 9,
    backgroundColor: "rgba(255,250,247,0.88)",
    borderWidth: 1,
    borderColor: "rgba(184,95,123,0.12)",
    boxShadow: "0 12px 24px rgba(116,74,89,0.1), inset 0 1px 1px rgba(255,255,255,0.9)",
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
  },
  creationRewardPillPulse: {
    backgroundColor: "#fff1d2",
    borderColor: "rgba(215,162,78,0.38)",
    transform: [{ translateY: -1 }],
  },
  creationRewardPillIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#FDF3D6",
    alignItems: "center",
    justifyContent: "center",
  },
  creationRewardPillCopy: {
    flex: 1,
    minWidth: 0,
  },
  creationRewardPillLabel: {
    color: colors.muted,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "900",
  },
  creationRewardPillValue: {
    color: colors.ink,
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "900",
  },
  creationRewardPillDelta: {
    color: colors.accent,
    fontSize: 23,
    lineHeight: 28,
    fontWeight: "900",
  },
  creationRewardToast: {
    position: "absolute",
    left: 16,
    right: 16,
    top: 86,
    zIndex: 20,
    borderRadius: 24,
    padding: 12,
    backgroundColor: "rgba(255,250,252,0.96)",
    borderWidth: 1,
    borderColor: "rgba(184,95,123,0.16)",
    boxShadow: "0 18px 38px rgba(116,74,89,0.18)",
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  creationRewardIcon: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: "#FDF3D6",
    alignItems: "center",
    justifyContent: "center",
  },
  creationRewardCopy: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  creationRewardTitle: {
    color: colors.ink,
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "900",
  },
  creationRewardText: {
    color: colors.muted,
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "700",
  },
  creationHub: {
    position: "relative",
    height: "calc(100dvh - 4px)" as never,
    maxHeight: "calc(100dvh - 4px)" as never,
    borderRadius: 0,
    overflow: "hidden",
    backgroundColor: "#fffaf7",
    backgroundImage: "linear-gradient(180deg, #fffaf7 0%, #fff0f5 48%, #eef4f6 100%)" as never,
    marginHorizontal: -18,
    marginTop: -20,
    marginBottom: -24,
  },
  creationHubConceptImage: {
    position: "absolute",
    left: 0,
    top: 0,
    width: "100%",
    height: "100%",
  },
  creationHubVeil: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    backgroundImage: "linear-gradient(180deg, rgba(255,250,247,0.9) 0%, rgba(255,250,247,0.58) 16%, rgba(255,250,247,0.08) 42%, rgba(255,250,247,0.18) 74%, rgba(255,250,247,0.86) 100%)" as never,
  },
  creationHubBackButton: {
    position: "absolute",
    left: 18,
    top: "calc(14px + env(safe-area-inset-top))" as never,
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: "rgba(255,255,255,0.62)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.8)",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 4,
  },
  creationHubTitleBlock: {
    position: "absolute",
    left: 28,
    top: "calc(54px + env(safe-area-inset-top))" as never,
    zIndex: 3,
    gap: 3,
  },
  creationHubKicker: {
    color: colors.accentDark,
    fontSize: 15,
    lineHeight: 19,
    fontWeight: "800",
  },
  creationHubScreenTitle: {
    color: colors.ink,
    fontSize: 31,
    lineHeight: 38,
    fontWeight: "900",
    letterSpacing: 0,
  },
  creationHubScreenSubtitle: {
    color: "rgba(127,83,94,0.72)",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "700",
  },
  creationHubPetHotspot: {
    position: "absolute",
    left: 46,
    right: 46,
    top: "calc(214px + env(safe-area-inset-top))" as never,
    height: 202,
    borderRadius: 42,
    zIndex: 5,
  },
  creationHubCloudPetCover: {
    position: "absolute",
    left: "50%",
    top: "calc(146px + env(safe-area-inset-top))" as never,
    width: 172,
    height: 210,
    marginLeft: -86,
    zIndex: 4,
    alignItems: "center",
    justifyContent: "center",
  },
  creationHubCloudPetMask: {
    position: "absolute",
    left: -2,
    right: -2,
    top: 34,
    bottom: 0,
    borderRadius: 58,
    backgroundColor: "rgba(255,250,247,0.92)",
    boxShadow: "0 18px 34px rgba(116,74,89,0.16), inset 0 1px 1px rgba(255,255,255,0.9)",
  },
  creationHubCloudPetGlow: {
    width: 172,
    height: 190,
    marginTop: 0,
    overflow: "visible",
  },
  creationHubFootprintHotspot: {
    position: "absolute",
    left: 24,
    bottom: "max(112px, calc(106px + env(safe-area-inset-bottom)))" as never,
    width: "44%",
    height: 146,
    borderRadius: 34,
    zIndex: 4,
  },
  creationHubGameHotspot: {
    position: "absolute",
    right: 24,
    bottom: "max(112px, calc(106px + env(safe-area-inset-bottom)))" as never,
    width: "44%",
    height: 146,
    borderRadius: 34,
    zIndex: 4,
  },
  creationHubHotspotButton: {
    flex: 1,
    borderRadius: 34,
    justifyContent: "flex-end",
    padding: 6,
  },
  creationHubPetLabel: {
    alignSelf: "center",
    minWidth: 152,
    maxWidth: 190,
    borderRadius: 24,
    paddingHorizontal: 13,
    paddingVertical: 9,
    backgroundColor: "rgba(255,252,248,0.88)",
    borderWidth: 1.5,
    borderColor: "rgba(255,255,255,0.9)",
    boxShadow: "0 16px 30px rgba(116,74,89,0.15), inset 0 1px 1px rgba(255,255,255,0.9)",
    gap: 2,
  },
  creationHubSmallLabel: {
    borderRadius: 24,
    paddingHorizontal: 13,
    paddingVertical: 11,
    backgroundColor: "rgba(255,252,248,0.88)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.82)",
    boxShadow: "0 14px 24px rgba(116,74,89,0.13), inset 0 1px 1px rgba(255,255,255,0.9)",
    gap: 3,
  },
  creationHubLabelTitle: {
    color: colors.ink,
    fontSize: 19,
    lineHeight: 24,
    fontWeight: "900",
    textAlign: "center",
  },
  creationHubLabelBadge: {
    alignSelf: "center",
    color: colors.accentDark,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "900",
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 999,
    backgroundColor: "rgba(253,235,241,0.82)",
    overflow: "hidden",
  },
  creationHubLabelText: {
    color: colors.muted,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "800",
    textAlign: "center",
  },
  creationCloudClusterTop: {
    position: "absolute",
    left: -28,
    top: 20,
    width: 150,
    height: 90,
    borderRadius: 60,
    backgroundColor: "rgba(255,255,255,0.44)",
    boxShadow: "70px 12px 0 rgba(253,235,241,0.42), 180px 8px 0 rgba(255,255,255,0.5)",
  },
  creationCloudClusterBottom: {
    position: "absolute",
    right: -36,
    bottom: 34,
    width: 168,
    height: 82,
    borderRadius: 60,
    backgroundColor: "rgba(255,255,255,0.52)",
    boxShadow: "-86px 16px 0 rgba(227,238,244,0.36), -190px -8px 0 rgba(253,243,214,0.25)",
  },
  creationIsland: {
    position: "relative",
    minHeight: 154,
    borderRadius: 30,
    padding: 0,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.86)",
    boxShadow: "0 20px 34px rgba(116,74,89,0.11)",
    gap: 9,
    overflow: "hidden",
  },
  creationIslandPressed: {
    opacity: 0.9,
    transform: [{ translateY: 1 }],
  },
  creationPetIsland: {
    minHeight: 318,
    backgroundColor: "rgba(255,248,251,0.5)",
    backgroundImage: "linear-gradient(180deg, rgba(255,255,255,0.62), rgba(253,235,241,0.44))" as never,
  },
  creationFootprintIsland: {
    flex: 1,
    minHeight: 238,
    backgroundColor: "rgba(255,247,245,0.54)",
    backgroundImage: "linear-gradient(180deg, rgba(255,255,255,0.58), rgba(253,243,214,0.38))" as never,
  },
  creationGameIsland: {
    flex: 1,
    minHeight: 238,
    backgroundColor: "rgba(249,246,255,0.54)",
    backgroundImage: "linear-gradient(180deg, rgba(255,255,255,0.58), rgba(238,232,246,0.42))" as never,
  },
  creationIslandHeroImage: {
    width: "100%",
    height: 250,
    marginTop: 4,
  },
  creationSmallIslandImage: {
    width: "118%",
    height: 150,
    marginLeft: "-9%" as never,
    marginTop: 6,
  },
  creationIslandOverlayTop: {
    position: "absolute",
    top: 12,
    right: 12,
    minHeight: 30,
    borderRadius: 999,
    paddingHorizontal: 10,
    backgroundColor: "rgba(255,255,255,0.82)",
    borderWidth: 1,
    borderColor: "rgba(184,95,123,0.12)",
    justifyContent: "center",
  },
  creationIslandCaption: {
    position: "absolute",
    left: 14,
    right: 14,
    bottom: 14,
    borderRadius: 24,
    padding: 13,
    backgroundColor: "rgba(255,255,255,0.86)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.72)",
    gap: 4,
  },
  creationIslandCaptionSmall: {
    position: "absolute",
    left: 10,
    right: 10,
    bottom: 10,
    borderRadius: 21,
    padding: 10,
    backgroundColor: "rgba(255,255,255,0.88)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.72)",
    gap: 2,
  },
  creationIslandTall: {
    flex: 1,
    minWidth: 0,
  },
  creationIslandHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  creationIslandIcon: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.75)",
  },
  creationIslandIconPet: {
    backgroundColor: "#FDEBF1",
  },
  creationIslandIconFootprint: {
    backgroundColor: "#FDF3D6",
  },
  creationIslandIconGame: {
    backgroundColor: "#E3EEF4",
  },
  creationIslandTag: {
    color: colors.accentDark,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "900",
  },
  creationIslandTitle: {
    color: colors.ink,
    fontSize: 19,
    lineHeight: 23,
    fontWeight: "900",
  },
  creationIslandText: {
    color: colors.muted,
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "700",
  },
  creationIslandMeta: {
    color: colors.accentDark,
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "900",
  },
  creationHubPetRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  creationHubPetImage: {
    width: 82,
    height: 82,
    borderRadius: 30,
    backgroundColor: "#fff",
  },
  creationHubPetCopy: {
    flex: 1,
    minWidth: 0,
    gap: 5,
  },
  creationIslandGrid: {
    flexDirection: "row",
    gap: 12,
  },
  creationIslandHalf: {
    flex: 1,
    minWidth: 0,
  },
  creationTownLogCard: {
    gap: 8,
    backgroundColor: "rgba(255,255,255,0.82)",
  },
  creationCabin: {
    gap: 12,
  },
  creationCabinStageCard: {
    overflow: "hidden",
    gap: 13,
    padding: 12,
    borderRadius: 32,
    backgroundColor: "rgba(255,250,247,0.96)",
    backgroundImage: "linear-gradient(160deg, rgba(255,250,247,0.98), rgba(253,235,241,0.48), rgba(227,238,244,0.24))" as never,
    boxShadow: "0 18px 40px rgba(116,74,89,0.1), inset 0 1px 2px rgba(255,255,255,0.94)",
  },
  creationCabinStageWrap: {
    position: "relative",
    minHeight: 456,
    borderRadius: 32,
    overflow: "hidden",
    backgroundColor: "#f4dcc4",
    boxShadow: "0 18px 34px rgba(116,74,89,0.16)",
  },
  creationCabinInteriorImage: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    width: "100%",
    height: "100%",
  },
  creationCabinPetStage: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 58,
    bottom: 16,
    borderRadius: 26,
    overflow: "hidden",
    backgroundColor: "rgba(255,255,255,0)",
    zIndex: 2,
  },
  creationCabinSummonStage: {
    position: "absolute",
    left: 18,
    right: 18,
    top: 80,
    bottom: 28,
    zIndex: 2,
    alignItems: "center",
    justifyContent: "center",
  },
  creationCabinSummonPanel: {
    width: "100%",
    maxWidth: 285,
    borderRadius: 28,
    paddingHorizontal: 18,
    paddingVertical: 18,
    backgroundColor: "rgba(255,250,247,0.9)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.78)",
    boxShadow: "0 18px 38px rgba(116,74,89,0.14), inset 0 1px 1px rgba(255,255,255,0.9)",
    alignItems: "center",
    gap: 9,
  },
  creationCabinSummonIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "rgba(255,255,255,0.76)",
    borderWidth: 1,
    borderColor: "rgba(184,95,123,0.12)",
    alignItems: "center",
    justifyContent: "center",
  },
  creationCabinSummonTitle: {
    color: colors.ink,
    fontSize: 18,
    lineHeight: 23,
    fontWeight: "900",
    textAlign: "center",
  },
  creationCabinSummonText: {
    color: colors.muted,
    fontSize: 13,
    lineHeight: 19,
    fontWeight: "700",
    textAlign: "center",
  },
  creationCabinSummonButton: {
    minHeight: 46,
    borderRadius: 999,
    paddingHorizontal: 18,
    backgroundColor: colors.accent,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    boxShadow: "0 13px 25px rgba(184,95,123,0.24)",
  },
  creationCabinSummonButtonPressed: {
    transform: [{ translateY: 1 }],
    opacity: 0.92,
  },
  creationCabinSummonButtonDisabled: {
    opacity: 0.68,
  },
  creationCabinSummonButtonText: {
    color: "#fff",
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "900",
  },
  creationGranaryButton: {
    position: "absolute",
    right: 12,
    bottom: 12,
    zIndex: 5,
    minWidth: 86,
    height: 62,
    borderRadius: 26,
    paddingHorizontal: 15,
    backgroundColor: "rgba(255,249,241,0.92)",
    borderWidth: 1,
    borderColor: "rgba(184,95,123,0.16)",
    boxShadow: "0 14px 28px rgba(116,74,89,0.18), inset 0 1px 1px rgba(255,255,255,0.85)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
  },
  creationGranaryButtonText: {
    color: colors.accentDark,
    fontSize: 13,
    lineHeight: 16,
    fontWeight: "900",
  },
  creationGranaryDrawer: {
    borderRadius: 26,
    padding: 13,
    backgroundColor: "rgba(255,255,255,0.9)",
    borderWidth: 1,
    borderColor: "rgba(184,95,123,0.1)",
    boxShadow: "0 16px 32px rgba(116,74,89,0.11)",
    gap: 11,
  },
  creationGranaryHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  creationGranaryTitle: {
    color: colors.ink,
    fontSize: 16,
    lineHeight: 21,
    fontWeight: "900",
  },
  creationHeroCard: {
    overflow: "hidden",
    gap: 12,
    backgroundColor: "rgba(255,255,255,0.96)",
    backgroundImage: "linear-gradient(135deg, rgba(255,246,239,0.98), rgba(250,231,239,0.72) 46%, rgba(236,244,246,0.72))" as never,
    borderColor: "rgba(255,255,255,0.86)",
    boxShadow: "0 18px 42px rgba(116,74,89,0.08), inset 0 1px 2px rgba(255,255,255,0.92)",
  },
  creationHeroTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  creationHeroBadge: {
    minHeight: 32,
    borderRadius: 999,
    paddingHorizontal: 11,
    backgroundColor: "rgba(255,255,255,0.72)",
    borderWidth: 1,
    borderColor: "rgba(184,95,123,0.12)",
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  creationHeroBadgeText: {
    color: colors.accentDark,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "900",
  },
  creationHeroTitle: {
    color: colors.ink,
    fontSize: 24,
    lineHeight: 30,
    fontWeight: "900",
  },
  creationHeroText: {
    color: colors.muted,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "600",
  },
  creationPetStage: {
    position: "relative",
    minHeight: 260,
    borderRadius: 28,
    overflow: "hidden",
    backgroundColor: "#fff4ef",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.9)",
    boxShadow: "0 20px 42px rgba(82,61,66,0.12)",
  },
  creationPetHeroImage: {
    width: "100%",
    height: 260,
  },
  creationPetStageShade: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: 96,
    backgroundImage: "linear-gradient(180deg, rgba(50,35,36,0), rgba(50,35,36,0.38))" as never,
  },
  creationPetInfoPill: {
    position: "absolute",
    left: 14,
    right: 14,
    bottom: 14,
    borderRadius: 22,
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: "rgba(255,255,255,0.88)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.72)",
    gap: 2,
  },
  creationPetInfoTitle: {
    color: colors.ink,
    fontSize: 18,
    lineHeight: 23,
    fontWeight: "900",
  },
  creationPetInfoMeta: {
    color: colors.muted,
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "800",
  },
  creationMeters: {
    flexDirection: "row",
    gap: 9,
  },
  creationMeter: {
    flex: 1,
    minWidth: 0,
    borderRadius: 22,
    padding: 10,
    backgroundColor: "rgba(255,255,255,0.76)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.82)",
    boxShadow: "0 10px 18px rgba(116,74,89,0.07), inset 0 1px 1px rgba(255,255,255,0.9)",
    gap: 7,
  },
  creationMeterHead: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 6,
  },
  creationMeterLabel: {
    color: colors.muted,
    fontSize: 11,
    lineHeight: 14,
    fontWeight: "900",
  },
  creationMeterValue: {
    color: colors.ink,
    fontSize: 12,
    lineHeight: 14,
    fontWeight: "900",
  },
  creationMeterTrack: {
    height: 8,
    borderRadius: 999,
    backgroundColor: "rgba(129,111,116,0.12)",
    overflow: "hidden",
  },
  creationMeterFill: {
    height: "100%",
    borderRadius: 999,
  },
  creationSleepNotice: {
    minHeight: 38,
    borderRadius: 18,
    paddingHorizontal: 12,
    paddingVertical: 9,
    backgroundColor: "rgba(255,255,255,0.74)",
    borderWidth: 1,
    borderColor: "rgba(184,95,123,0.12)",
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  creationSleepNoticeText: {
    flex: 1,
    minWidth: 0,
    color: colors.muted,
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "800",
  },
  creationResourceRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  creationResourcePill: {
    flexGrow: 1,
    minWidth: "30%",
    minHeight: 46,
    borderRadius: 18,
    paddingHorizontal: 10,
    paddingVertical: 8,
    backgroundColor: "rgba(255,255,255,0.74)",
    borderWidth: 1,
    borderColor: "rgba(184,95,123,0.1)",
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  creationResourceIcon: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: colors.accentSoft,
    alignItems: "center",
    justifyContent: "center",
  },
  creationResourceText: {
    minWidth: 0,
    gap: 1,
  },
  creationResourceLabel: {
    color: colors.faint,
    fontSize: 11,
    lineHeight: 14,
    fontWeight: "800",
  },
  creationResourceValue: {
    color: colors.ink,
    fontSize: 13,
    lineHeight: 16,
    fontWeight: "900",
  },
  petMemoryTrailSection: {
    gap: 13,
    paddingHorizontal: 2,
    paddingTop: 2,
  },
  petMemoryTrailHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
    gap: 12,
  },
  petMemoryTrailTitleBlock: {
    flex: 1,
    minWidth: 0,
    gap: 5,
  },
  petMemoryTrailKicker: {
    alignSelf: "flex-start",
    minHeight: 28,
    borderRadius: 999,
    paddingHorizontal: 10,
    backgroundColor: "rgba(255,255,255,0.62)",
    borderWidth: 1,
    borderColor: "rgba(184,95,123,0.1)",
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  petMemoryTrailKickerText: {
    color: colors.accentDark,
    fontSize: 12,
    lineHeight: 15,
    fontWeight: "900",
  },
  petMemoryTrailTitle: {
    color: colors.ink,
    fontSize: 19,
    lineHeight: 24,
    fontWeight: "900",
  },
  petMemoryTrailCount: {
    color: colors.accentDark,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "900",
    paddingBottom: 2,
  },
  petMemoryTrail: {
    gap: 0,
  },
  petMemoryTrailRow: {
    flexDirection: "row",
    alignItems: "stretch",
    gap: 11,
    minHeight: 92,
  },
  petMemoryRail: {
    width: 26,
    alignItems: "center",
  },
  petMemoryNode: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: "rgba(255,255,255,0.92)",
    alignItems: "center",
    justifyContent: "center",
    boxShadow: "0 8px 14px rgba(116,74,89,0.12)",
  },
  petMemoryNodeDot: {
    width: 7,
    height: 7,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.94)",
  },
  petMemoryRailLine: {
    flex: 1,
    width: 2,
    marginTop: 5,
    marginBottom: 5,
    borderRadius: 999,
    backgroundColor: "rgba(184,95,123,0.13)",
  },
  petMemoryNote: {
    flex: 1,
    minWidth: 0,
    marginBottom: 12,
    borderRadius: 24,
    paddingHorizontal: 13,
    paddingVertical: 12,
    borderWidth: 1,
    boxShadow: "0 12px 26px rgba(116,74,89,0.06), inset 0 1px 1px rgba(255,255,255,0.72)",
    gap: 7,
  },
  petMemoryNoteHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
  },
  petMemorySummary: {
    flex: 1,
    minWidth: 0,
    color: colors.ink,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "900",
  },
  petMemoryTag: {
    minHeight: 25,
    borderRadius: 999,
    paddingHorizontal: 9,
    alignItems: "center",
    justifyContent: "center",
  },
  petMemoryTagText: {
    color: colors.accentDark,
    fontSize: 11,
    lineHeight: 14,
    fontWeight: "900",
  },
  petMemoryMeta: {
    color: colors.faint,
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "800",
  },
  petMemoryActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "flex-start",
    gap: 7,
    paddingTop: 2,
  },
  petMemoryTrailAction: {
    minHeight: 31,
    borderRadius: 999,
    paddingHorizontal: 10,
    backgroundColor: "rgba(255,255,255,0.76)",
    borderWidth: 1,
    borderColor: "rgba(184,95,123,0.1)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
  },
  petMemoryTrailActionActive: {
    backgroundColor: colors.accent,
    borderColor: "rgba(184,95,123,0.16)",
    boxShadow: "0 8px 15px rgba(184,95,123,0.16)",
  },
  petMemoryTrailActionDanger: {
    backgroundColor: "rgba(255,255,255,0.62)",
  },
  petMemoryTrailActionDisabled: {
    opacity: 0.55,
  },
  petMemoryTrailActionText: {
    color: colors.accentDark,
    fontSize: 11,
    lineHeight: 14,
    fontWeight: "900",
  },
  petMemoryTrailActionTextActive: {
    color: "#fff",
  },
  petMemoryEmptyTrail: {
    minHeight: 78,
    borderRadius: 26,
    paddingHorizontal: 14,
    paddingVertical: 13,
    backgroundColor: "rgba(255,255,255,0.58)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.82)",
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    boxShadow: "0 12px 24px rgba(116,74,89,0.05)",
  },
  petMemoryEmptyIcon: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: colors.accentSoft,
    borderWidth: 1,
    borderColor: "rgba(184,95,123,0.12)",
    alignItems: "center",
    justifyContent: "center",
  },
  petMemoryEmptyCopy: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  petMemoryEmptyTitle: {
    color: colors.ink,
    fontSize: 15,
    lineHeight: 19,
    fontWeight: "900",
  },
  petMemoryEmptyText: {
    color: colors.muted,
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "700",
  },
  creationLevelText: {
    color: colors.accentDark,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "900",
  },
  creationActionRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 8,
  },
  creationCloudPetProfile: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    borderRadius: 22,
    padding: 12,
    backgroundColor: "#fff9fb",
    borderWidth: 1,
    borderColor: "rgba(184,95,123,0.12)",
  },
  creationCloudPetPortrait: {
    width: 92,
    height: 92,
    borderRadius: 24,
    backgroundColor: "#fff2f5",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  creationCloudPetPortraitLive2D: {
    width: 118,
    height: 118,
    overflow: "visible",
    backgroundColor: "transparent",
  },
  creationCloudPetProfileLive2DStage: {
    width: 118,
    height: 118,
    position: "relative",
    overflow: "visible",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  creationCloudPetProfileLive2DText: {
    color: colors.accentDark,
    fontSize: 12,
    lineHeight: 15,
    fontWeight: "900",
  },
  creationCloudPetImage: {
    width: 84,
    height: 84,
  },
  creationCloudPetCopy: {
    flex: 1,
    gap: 3,
  },
  creationCloudPetTitle: {
    color: colors.ink,
    fontSize: 16,
    lineHeight: 21,
    fontWeight: "900",
  },
  creationCloudPetMeta: {
    color: colors.accentDark,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "900",
  },
  creationPetDescription: {
    color: colors.muted,
    fontSize: 13,
    lineHeight: 19,
    fontWeight: "700",
  },
  creationIdentityPill: {
    minHeight: 52,
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: "#fff9fb",
    borderWidth: 1,
    borderColor: "rgba(184,95,123,0.1)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  creationIdentityLabel: {
    color: colors.muted,
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "800",
  },
  creationIdentityValue: {
    color: colors.accentDark,
    fontSize: 17,
    lineHeight: 22,
    fontWeight: "900",
  },
  creationDecorRow: {
    flexDirection: "row",
    gap: 8,
  },
  creationDecorInput: {
    flex: 1,
    minWidth: 0,
  },
  footprintForm: {
    gap: 10,
  },
  footprintNoteInput: {
    minHeight: 88,
    paddingTop: 14,
    textAlignVertical: "top",
  },
  footprintCoordRow: {
    flexDirection: "row",
    gap: 8,
  },
  footprintCoordInput: {
    flex: 1,
    minWidth: 0,
  },
  creationFootprintList: {
    gap: 9,
  },
  creationFootprintItem: {
    borderRadius: 20,
    padding: 12,
    backgroundColor: "#fff9fb",
    borderWidth: 1,
    borderColor: "rgba(184,95,123,0.09)",
    gap: 10,
  },
  creationFootprintText: {
    gap: 3,
  },
  creationFootprintTitle: {
    color: colors.ink,
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "900",
  },
  creationFootprintMeta: {
    color: colors.muted,
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "700",
  },
  creationFootprintCoords: {
    color: colors.faint,
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "700",
  },
  creationFootprintActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  creationFootprintPage: {
    gap: 12,
  },
  creationJourneyCard: {
    position: "relative",
    gap: 13,
    minHeight: 708,
    overflow: "hidden",
    borderRadius: 32,
    padding: 14,
    backgroundColor: "rgba(255,250,247,0.98)",
    backgroundImage: "linear-gradient(180deg, rgba(255,250,247,0.96), rgba(253,235,241,0.5), rgba(253,243,214,0.28))" as never,
  },
  creationJourneySceneImage: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    width: "100%",
    height: "100%",
  },
  creationJourneySceneVeil: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    backgroundImage: "linear-gradient(180deg, rgba(255,250,247,0.18), rgba(255,250,247,0.42) 26%, rgba(255,250,247,0.84) 86%)" as never,
  },
  creationJourneyPetStage: {
    alignSelf: "center",
    width: "100%",
    maxWidth: 260,
    height: 236,
    marginTop: -8,
    marginBottom: -10,
    zIndex: 2,
  },
  creationJourneyBackdrop: {
    position: "absolute",
    right: -72,
    top: 10,
    width: 280,
    height: 220,
    opacity: 0.36,
  },
  creationJourneyHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingTop: 4,
    paddingHorizontal: 2,
    zIndex: 2,
  },
  creationCompass: {
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: "#FDF3D6",
    borderWidth: 1,
    borderColor: "rgba(184,95,123,0.1)",
    alignItems: "center",
    justifyContent: "center",
  },
  creationJourneyCopy: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  creationPolaroidRail: {
    position: "relative",
    gap: 14,
    paddingLeft: 20,
    paddingTop: 6,
    paddingBottom: 4,
    borderLeftWidth: 2,
    borderLeftColor: "rgba(229,111,137,0.34)",
    zIndex: 2,
  },
  creationPolaroid: {
    position: "relative",
    minHeight: 124,
    borderRadius: 22,
    padding: 15,
    paddingRight: 94,
    backgroundColor: "rgba(255,255,255,0.88)",
    borderWidth: 1,
    borderColor: "rgba(184,95,123,0.13)",
    boxShadow: "0 14px 28px rgba(116,74,89,0.12)",
    gap: 4,
    transform: [{ rotate: "-0.5deg" }],
  },
  creationPolaroidPhoto: {
    position: "absolute",
    right: 14,
    top: 18,
    width: 72,
    height: 58,
    borderRadius: 7,
    backgroundColor: "#BFD9E5",
    backgroundImage: "linear-gradient(145deg, #b7d9e7, #f5d4dd)" as never,
    borderWidth: 5,
    borderColor: "#fff",
    transform: [{ rotate: "4deg" }],
    alignItems: "center",
    justifyContent: "center",
  },
  creationTimelineHeart: {
    position: "absolute",
    left: -30,
    top: 34,
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: "#FDEBF1",
    borderWidth: 1,
    borderColor: "rgba(184,95,123,0.22)",
    alignItems: "center",
    justifyContent: "center",
  },
  creationPolaroidPin: {
    position: "absolute",
    right: 12,
    top: 10,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#FDEBF1",
    alignItems: "center",
    justifyContent: "center",
  },
  creationFootprintFormCard: {
    gap: 11,
    borderRadius: 28,
    backgroundColor: "rgba(255,255,255,0.92)",
    boxShadow: "0 14px 28px rgba(116,74,89,0.08)",
  },
  footprintModalLayer: {
    position: "fixed",
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    zIndex: 44,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 18,
    paddingTop: "calc(18px + env(safe-area-inset-top))" as never,
    paddingBottom: "calc(18px + env(safe-area-inset-bottom))" as never,
  },
  footprintModalBackdrop: {
    ...StyleSheet.absoluteFill,
    backgroundColor: "rgba(54,38,45,0.42)",
  },
  footprintModalCard: {
    width: "100%",
    maxWidth: 430,
    borderRadius: 30,
    gap: 13,
    backgroundColor: "rgba(255,253,251,0.98)",
    borderColor: "rgba(255,255,255,0.86)",
    boxShadow: "0 28px 64px rgba(74,47,58,0.26), inset 0 1px 1px rgba(255,255,255,0.9)",
  },
  footprintModalHint: {
    color: colors.muted,
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "700",
    marginTop: 3,
  },
  footprintModalClose: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.panelSoft,
    borderWidth: 1,
    borderColor: "rgba(184,95,123,0.12)",
    alignItems: "center",
    justifyContent: "center",
  },
  footprintModalCloseText: {
    color: colors.accentDark,
    fontSize: 19,
    lineHeight: 21,
    fontWeight: "900",
  },
  creationShopGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  creationFoodCard: {
    flex: 1,
    minWidth: 148,
    borderRadius: 23,
    padding: 13,
    backgroundColor: "rgba(255,249,251,0.92)",
    borderWidth: 1,
    borderColor: "rgba(184,95,123,0.09)",
    boxShadow: "0 10px 20px rgba(116,74,89,0.06)",
    gap: 8,
  },
  creationFoodTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  creationFoodIcon: {
    width: 36,
    height: 36,
    borderRadius: 16,
    backgroundColor: colors.panelSoft,
    alignItems: "center",
    justifyContent: "center",
  },
  creationFoodCount: {
    color: colors.accentDark,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "900",
  },
  creationFoodTitle: {
    color: colors.ink,
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "900",
  },
  creationFoodDescription: {
    color: colors.muted,
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "700",
  },
  creationGameCard: {
    gap: 10,
    backgroundColor: "rgba(255,255,255,0.9)",
  },
  creationPlayground: {
    gap: 12,
  },
  creationPuzzleEnvelope: {
    position: "relative",
    gap: 10,
    minHeight: 520,
    paddingTop: 132,
    borderRadius: 32,
    paddingHorizontal: 16,
    paddingBottom: 16,
    backgroundColor: "#fffafb",
    backgroundImage: "linear-gradient(180deg, rgba(255,250,252,0.98), rgba(253,235,241,0.68) 52%, rgba(227,238,244,0.36))" as never,
    overflow: "hidden",
  },
  creationPuzzleSceneImage: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    width: "100%",
    height: "100%",
  },
  creationPuzzleSceneVeil: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    backgroundImage: "linear-gradient(180deg, rgba(255,250,252,0.08), rgba(255,250,252,0.36) 36%, rgba(255,250,252,0.92) 78%)" as never,
  },
  creationPuzzlePetStage: {
    alignSelf: "center",
    width: "100%",
    maxWidth: 260,
    height: 232,
    marginTop: -12,
    marginBottom: -8,
    zIndex: 2,
  },
  creationPuzzleBackdrop: {
    position: "absolute",
    top: -36,
    alignSelf: "center",
    width: 300,
    height: 230,
    opacity: 0.82,
  },
  creationPuzzleTopLine: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10,
    zIndex: 1,
  },
  creationPuzzleHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  creationPuzzleBadge: {
    minHeight: 32,
    borderRadius: 999,
    paddingHorizontal: 11,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "rgba(253,235,241,0.88)",
    borderWidth: 1,
    borderColor: "rgba(184,95,123,0.12)",
  },
  creationPuzzleBadgeText: {
    color: colors.accentDark,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "900",
  },
  creationPuzzleStars: {
    flexDirection: "row",
    gap: 2,
  },
  creationPuzzleQuestion: {
    color: colors.ink,
    fontSize: 21,
    lineHeight: 29,
    fontWeight: "900",
    textAlign: "center",
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 24,
    backgroundColor: "rgba(255,255,255,0.68)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.82)",
    zIndex: 1,
  },
  creationPuzzleOptions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    zIndex: 1,
  },
  creationPuzzleOption: {
    flexGrow: 1,
    minWidth: "100%",
    minHeight: 45,
    borderRadius: 999,
    paddingHorizontal: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,248,251,0.92)",
    borderWidth: 1,
    borderColor: "rgba(184,95,123,0.1)",
    boxShadow: "0 8px 16px rgba(116,74,89,0.05)",
  },
  creationPuzzleOptionActive: {
    backgroundColor: "#E3EEF4",
    borderColor: "rgba(89,142,166,0.34)",
    boxShadow: "0 10px 20px rgba(89,142,166,0.13)",
  },
  creationPuzzleOptionText: {
    color: colors.muted,
    fontSize: 14,
    lineHeight: 19,
    fontWeight: "900",
  },
  creationPuzzleOptionTextActive: {
    color: colors.accentDark,
  },
  creationPlaygroundRewardCard: {
    gap: 8,
    borderRadius: 28,
    backgroundColor: "rgba(255,255,255,0.88)",
  },
  creationActionItem: {
    borderBottomWidth: 1,
    borderBottomColor: "rgba(184,95,123,0.08)",
    paddingVertical: 10,
    gap: 2,
  },
  creationActionTitle: {
    color: colors.ink,
    fontSize: 14,
    lineHeight: 19,
    fontWeight: "800",
  },
  creationActionMeta: {
    color: colors.faint,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "700",
  },
});
